### ISSUE TITLE
Ender Dragon

### ISSUE THREAD

**Issue by ShaneBeee** [MLG-Fortress/ExtraHardMode#104]
So the problem I'm having with the dragon is, she respawns, but up at like 255, and she is stuck there, doesn't move.

Is this a problem other servers are having?

**Comment by RoboMWM** [comment]
Server version, plugin version? `/version extrahardmode`

**Comment by ShaneBolenback** [comment]
server version: CraftBukkit version git-Spigot-596221b-2c5c611 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Plugin version: ExtraHardMode version 3.12.1

**Comment by RoboMWM** [comment]
```java
{
                EntityHelper.spawn(new Location(world, 0, world.getMaxHeight() - 1, 0), EntityType.ENDER_DRAGON);
}
```

I'm guessing you have a block at 0, 254, 0...? But that wouldn't explain the dragon getting stuck... Wondering if the AI might be confused due to the new enderdragon fight sequence (since 1.9 iirc)?

**Comment by ShaneBeee** [comment]
Oh man that was so long ago. But Im PRETTY sure there wouldn't have been a block there. 
Dealing with some stuff in the Skript community I have come to find out the Dragon AI situation is messed since I believe like you said 1.9. Even if you use the Minecraft /summon command, it'll summon a dragon without AI.
Maybe this is something that cant be fixed?

Im just looking at the [Wiki](https://minecraft.gamepedia.com/Ender_Dragon) now, and I came across this
```
Commands[edit | edit source]
The /summon ender_dragon command, by default, summons a harmless ender dragon that hovers in place. Setting the DragonPhase tag (for instance by issuing /summon ender_dragon ~ ~ ~ {DragonPhase:0}) will create a normal ender dragon, but it will have no health bar since the bar is managed by the End's dragon fight status rather than by the dragon entity itself. If spawned away from the center of the map (X:0, Z:0), the dragon will first fly to the center before resuming normal behavior (see #Behavior).
```
Not sure if this helps you any.

**Comment by RoboMWM** [comment]
Likely the cause: https://korobi.io/network/spigot/channel/paper/logs/2018/11/13/#L835

**Comment by ShaneBeee** [comment]
Ah... well mystery solved for why it didnt work. Damn him. Hopefully they can PR and fix that
