### ISSUE TITLE
Suddenly difficulty change?

### ISSUE THREAD

**Issue by Zunfire** [MLG-Fortress/ExtraHardMode#108]
My players says monster suddenly have become almost impossible, and I agree, is there any way too change it??

It would be nice if EHM used ”difficulty=” in server.properties as multiplier to set monsters hit points.

**Comment by RoboMWM** [comment]
If you want to change mob health and the like, using something like MobManager would work. I think you should be able to toggle what sort of effects the mobs apply though... like you could remove the slow the zombies cause.

**Comment by Zunfire** [comment]
Thanks for fast respond.

I will have a look at it.

**Comment by RoboMWM** [comment]
¯\_(ツ)_/¯
