### ISSUE TITLE
177 - Pigzombies only attack one player 

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/ExtraHardMode#11]
Reported by @erik1988
From http://dev.bukkit.org/bukkit-plugins/fun-hard-mode/tickets/177-pigzombies-only-attack-one-player/

ehm version: 3.6.4 
 cb/spigot version: b69 (1.8.3)

Pigzombies in the nether only attacks one player. If we are two people going to the nether the pigzombies will only attack the player that went trough the portal first. No matter how much the other player is killing them.

This makes it to easy for players to farm pig zombies since they will be peaceful toward certain players as long as they entered nether second.

I have tried to turn of the "always aggressive" but they still only attack one player. I hope this bug is getting fixed soon, its been around for quite some time.

Config of EHM:

http://pastebin.com/wJs5garD

**Comment by RoboMWM** [comment]
Iirc, zombie pigmen would change their aggression if another player attacks them, but I'll have to double check this.

**Comment by erik1988** [comment]
No they would just run after that one player, no matter how much the others attacked him and even if he never attacked back. My solution was to make a fork and remove the pigzombie code, then it worked as vanilla, witch is better than only having them after one player. I have not tested this with the latest version so Im not sure if you have fixed it.

**Comment by RoboMWM** [comment]
Yea, I saw you remove a ton of stuff in your fork, and after going through all the old tickets I see why you did what you did.

I'll see if it's possible to perhaps toggle the aggression onEntityDamage perhaps, if there's nothing in the API to fix this directly.

**Comment by RoboMWM** [comment]
So as per the commit I wasn't able to reproduce this. Those that were attacked by the other player chased after that other player.

Unless you mean the entire mob of pigmen should be chasing after the attacking player?
