### ISSUE TITLE
Damage to tools on death uses the same number for both values.

### ISSUE THREAD

**Issue by Marcafk** [MLG-Fortress/ExtraHardMode#112]
The   "  # Percentage of all of the players items that will get lost on death. " Setting affects both the chance of an item getting damaged, as well as the durability damage if a tool is selected.
Expected value is for the durability damage to be set with"  Damage Tools By Percentage: 20" , But instead the setting above affects durability damage also.
This bug has persisted for many versions, I thought I should mention something.

**Comment by RoboMWM** [comment]
Isn't that the point...? Not sure what the issue is.

> an item getting damaged, as well as the durability damage if a tool is selected.

This seems like the same thing to me? Perhaps you can clarify?

**Comment by Marcafk** [comment]
Ok so the config looks like this: 
      Loose Items On Death:
        Enable: true
        # Percentage of all of the players items that will get lost on death.
        Percentage: 10
        # Damage some tools from the list instead of completely removing them.
        # Encourages players to use more valuable tools as they won't completely loose them on death.
        Damage Tools By Percentage: 30
        Keep Heavily Damaged Tools: true
        # Tool settings apply only to these tools
        Tools:
        - DIAMOND_SWORD
        - DIAMOND_SPADE
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        # These items will never be removed on death.
        Blacklisted Items: []

The first percentage sets how many items you loose. If I have 10 stacks one stack is lost (10%), or one tool from the list is selected to be damaged. The second number is set to 30, so a Diamond sword so selected should get 30% durability damage.
However it only receives 10% damage, since the top number appears to be getting used for both.
I hope this clarifies the problem.

**Comment by RoboMWM** [comment]
Yes that does (probably should've stated that a config option wasn't being used).

**Comment by RoboMWM** [comment]
Yup, a typo. Thanks for the report.
