### ISSUE TITLE
Suggestion: Alter how item loss is calculated or allow alternate setting using a config

### ISSUE THREAD

**Issue by Marcafk** [MLG-Fortress/ExtraHardMode#113]
The plugin as it stands will only cause inventory loss if you have at least enough stacks to be divisible by the selected percentage.
For instance with a 10% loss setting you will never loose any items if you only have 9 things or less in inventory or equipped.
It means you're completely immune to the effect of loss as long as you don't carry many items around. 
At minimum one item should be selected and then there should be a chance of loosing that item.

**Comment by RoboMWM** [comment]
Interesting. I guess it might be using an int in its calculation/result, and rounding down. Would like some ideas of how to go about this (minimum of 1 might be an okay fix for now).

**Comment by RoboMWM** [comment]
Interestingly (but not suprisingly) a lot of this code uses deprecated stuff.
