### ISSUE TITLE
Hungarian(UTF-8) letters

### ISSUE THREAD

**Issue by S3nS3IW00** [MLG-Fortress/ExtraHardMode#117]
The #116 problem is'nt solved!

"Hello dear Developer!

I am an hungarian developer, and I have problem with messages.yml. I translate the messages, but I can't write hungarian letters, beause this plugin is ignore them. I tried to write in "" but its ignored too. Please fix it! I need UTF-8 compatible!"

I show you a picture about this problem:
![kepernyofelvetel 244](https://user-images.githubusercontent.com/22691959/34915927-3ff22d52-f92f-11e7-9558-6020c8a5e3a2.png)

**Comment by RoboMWM** [comment]
You need to escape double quotation marks if you wish to use them. As for the rest, it's simply reading whatever bukkit returns from its parsing of the messages.yml. I do recall something about this in the spigot thread, can't recall where or what the solution was though.

**Comment by S3nS3IW00** [comment]
The double quotation is'nt help. The plugin ignore.

**Comment by RoboMWM** [comment]
Plugin uses Bukkit's YAML parsing. Have you tried running the file through a yaml parser?

**Comment by S3nS3IW00** [comment]
Without double qoutation the error is same, because does'nt matter I write quotation, or not. The yaml is valid with unicode(Example: á, é, ő). But the plugin is ignore them.

**Comment by S3nS3IW00** [comment]
I think the problem is in scoreboard manager. Because the scoreboard does'nt accept unicode characters, and you have blocked. I use chat message, and please enable unicode for chat message.

**Comment by RoboMWM** [comment]
Can you gist.github.com the file?

**Comment by S3nS3IW00** [comment]
Normal: https://gist.github.com/S3nS3IW00/6abef1e46a2287d03d41e0854a055c8f

Ignored(until restart): https://gist.github.com/S3nS3IW00/28b4d8cd22c1be3ba7574aa84e46dc58

**Comment by S3nS3IW00** [comment]
Note: The normal file same, that without double quotation.

**Comment by RoboMWM** [comment]
Weird. I could try recompiling with explicit UTF-8 encoding but that should only affect the literal strings in the code. What's your server startup arguments?

**Comment by S3nS3IW00** [comment]
What do you mean by argument?

**Comment by RoboMWM** [comment]
Your server start script, basically.

**Comment by S3nS3IW00** [comment]
I don't know lol. I did'nt edited anything of this, so default of paperspigot.

**Comment by RoboMWM** [comment]
Ah ok, yea I'm not sure how bukkit/java reacts to files with utf-8 characters that are not in ANSI (at least that's default on Java on Windows). Enforce Java to start in utf-8 by adding this arg before the `-jar`

`-Dfile.encoding=UTF-8`

**Comment by S3nS3IW00** [comment]
Thank you so much! This line is solved the problem! But you can put UTF-8 compatible in the plugin. My plugin is too use UTF-8 characters.

I have one more question. Some messages have "EHM" prefix, and it does'nt editable. Can you add edit for this?

**Comment by RoboMWM** [comment]
> But you can put UTF-8 compatible in the plugin. My plugin is too use UTF-8 characters.

Mind sharing how? I'd assume you're not using Bukkit's `YamlConfiguration` then.

> Some messages have "EHM" prefix, and it does'nt editable. Can you add edit for this?

#51 

I'll get to it when I get through other stuff on my to-do list, especially since it's an enhancement. (Since you asked me though I think it's okay to say that being a [patron ](https://patreon.com/RoboMWM) can help bump this up in priority.)

**Comment by S3nS3IW00** [comment]
I do'nt use `getConfig().set("", "");`, I use only `getConfig().get("");`.
I have few pictures about this.
(Note: I reset the script to default)
![kepernyofelvetel 279](https://user-images.githubusercontent.com/22691959/35288167-45b6ae52-0064-11e8-8d4a-1b75d63e1554.png)
![kepernyofelvetel 280](https://user-images.githubusercontent.com/22691959/35288195-52e97032-0064-11e8-80ed-f25e39ece8aa.png)
![2018-01-23_17 32 08](https://user-images.githubusercontent.com/22691959/35288206-57c70088-0064-11e8-87ae-869188292c37.png)
![kepernyofelvetel 278](https://user-images.githubusercontent.com/22691959/35288198-5508c2fa-0064-11e8-8f97-afa8d82bc058.png)

**Comment by RoboMWM** [comment]
Ah, that means you never set stuff in the config, so you're only "utf-8 compatible" if you only get. Ok thanks.

**Comment by S3nS3IW00** [comment]
I test it with set. It works fine. I do'nt know what is the problem with your plugin, because I never meet this problem. Your plugin is amazing, ang very usefull, only need to solve this. I try to search the "mistake" in the source, but I was'nt found nothing. Sorry.

**Comment by RoboMWM** [comment]
You set non-ANSI chars? Try characters like the section symbol... I remember having issues with another plugin that did this and had to resolve with the Java arg.

**Comment by S3nS3IW00** [comment]
I set this, and it works fine after restart. I show the code also. This string has symbol.
![kepernyofelvetel 283](https://user-images.githubusercontent.com/22691959/35357862-1aecb10c-0155-11e8-98aa-171a093e51d8.png)
![kepernyofelvetel 282](https://user-images.githubusercontent.com/22691959/35357858-1928318e-0155-11e8-99d1-320dcfaaa00b.png)
![2018-01-24_22 17 55](https://user-images.githubusercontent.com/22691959/35357857-16026aec-0155-11e8-86ec-be4275f2dee4.png)

**Comment by RoboMWM** [comment]
Well, I was more regarding literally inserting the symbols from code instead of taking it from a command or similar, since that's just likely passing it raw in and out. But ok.

Re: the other plugin I had issues with: https://dev.bukkit.org/projects/scs/issues/856

**Comment by S3nS3IW00** [comment]
I am sorry, because I am from Hungary and I don't understand perfectly what do you mean. I don't  know how to solve the problem.
