### ISSUE TITLE
PermissionsEX breaks things

### ISSUE THREAD

**Issue by adracamas** [MLG-Fortress/ExtraHardMode#119]
The mobs spawn just fine apparently.  But pex seems to be mixing with EHM and breaking the physics etc..

Interesting that a whole other plugin (Exotic Gardens) was throwing the error.  Other than in game where dirt would NOT fall like it's supposed to, you'd never know in the console something was wrong.

`This server is running CraftBukkit version git-Spigot-4bd94dc-e3b4cf5 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by RoboMWM** [comment]
I'm not sure what the issue is.

Is it that dirt doesn't fall when it should? I have no idea how PEX is supposed to be part of this. I'm assuming you have your permissions setup incorrectly maybe? I've used PEX with EHM before just fine (I now use LuckPerms).

**Comment by adracamas** [comment]
I'm not sure either. I built a solo/separate server specifically for EHM and one hiccup is that dirt isn't dropping.  Still working on it but it's good to know it SHOULD be working. I'll try and isolate it. Might have something to do with 1.12.2 ( Is that what you were running it on?) but I'll also try to use LuckPerms.

**Comment by RoboMWM** [comment]
Yes I use latest.

Check config, try ensuring you're not opped or in creative since that disables EHM mechanics (depending on what you've setup in config), or if you've given yourself the `*` permission you probably just gave yourself all of the exemption nodes.

**Comment by adracamas** [comment]
AH, I didn't realize that op/owner would be omitted from allowing the world physics from being active. Very interesting. I'll have to have someone non-op check (server is being made, not open yet)

I'll get back to you on that.

**Comment by RoboMWM** [comment]
As mentioned, check config. You can enable/disable this exemption iirc.

**Comment by adracamas** [comment]
Thank you so much.  That is EXACTLY what the issue was.
