### ISSUE TITLE
Per world setting does not work

### ISSUE THREAD

**Issue by jeddell** [MLG-Fortress/ExtraHardMode#120]
Tried to set this plugin to only work on one world on my server, but the feature carry across all worlds.  Tried to set the config bot ways mention in the wiki:

 Enabled Worlds: [rooHC, rooHC_the_end,rooHC_nether]

OR

Enabled Worlds: 
  - rooHC
  - rooHC_the_end
  - rooHC_nether

Nether method worked. I've had to disable this plugin due to the fact that I cant make it specific to worlds.

**Comment by RoboMWM** [comment]
Please provide the config.yml in full (you can paste here provided you use the proper github formatting as such:
```
    ```yml
    your config.yml contents here
    ```
```

**Comment by RoboMWM** [comment]
Resolved in https://github.com/MLG-Fortress/ExtraHardMode/commit/6d7ae48ae99c3baec68ea77702a66bb1380e5f81

https://www.spigotmc.org/threads/extra-hard-mode.129354/page-18#post-2946738
