### ISSUE TITLE
Detroying java

### ISSUE THREAD

**Issue by S3nS3IW00** [MLG-Fortress/ExtraHardMode#121]
Hello!

Im use spigot 1.12.2, and the plugin is Destroying Java. The latest problem occured when I kill a spider.

What is the problem?

**Comment by S3nS3IW00** [comment]
Sorry. Not your problem, the spigot is shit. The spigot have problem all my plugins.

Your plugin be updated soon?

**Comment by RoboMWM** [comment]
This plugin works on 1.12.2 so I don't see what needs updating. If you find anything specific not already in the issue tracker feel free to create an issue about it.
