### ISSUE TITLE
Could not pass event CraftItemEvent to ExtraHardMode v3.12.1

### ISSUE THREAD

**Issue by G4stavoM1ster** [MLG-Fortress/ExtraHardMode#127]
`08.10 00:45:15 [Server] ERROR Could not pass event CraftItemEvent to ExtraHardMode v3.12.1
08.10 00:45:15 [Server] INFO org.bukkit.event.EventException: null
08.10 00:45:15 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1983) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
08.10 00:45:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
08.10 00:45:15 [Server] INFO Caused by: java.lang.IllegalArgumentException: We can't check if a Player bypasses if there is no Player!
08.10 00:45:15 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO at com.extrahardmode.module.PlayerModule.playerBypasses(PlayerModule.java:64) ~[?:?]
08.10 00:45:15 [Server] INFO at com.extrahardmode.features.AntiFarming.onItemCrafted(AntiFarming.java:384) ~[?:?]
08.10 00:45:15 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor547.execute(Unknown Source) ~[?:?]
08.10 00:45:15 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[TacoSpigot.jar:git-TacoSpigot-"f8ba67d6"]
08.10 00:45:15 [Server] INFO ... 16 more`

**Comment by RoboMWM** [comment]
Hmm, do something other than players fire a crafting event? Or perhaps you have a plugin firing this event?

**Comment by RoboMWM** [comment]
Either disable the tnt crafting in config or figure out what plugin is firing CraftItemEvent with a null player. I'll try to mitigate regardless...
