### ISSUE TITLE
Mining mechanics testing

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#129]
Spigot 1.13.1 latest
EHM 1.13-alpha

The following mining mechanics are enabled on my server:

1. Stone can be mined only with iron and diamond pickaxes, and they wear out quickly.
2. Mining ore turns surrounding stone to cobble.
3. Cobble and dirt may cave in when disturbed.
4. Grass may cave in when disturbed.

Test results:

1. Confirmed.
2. Confirmed.
3. Cobble and dirt cave in.
4. **FAIL**: Grass does not cave in, probably a consequence of the material name change to **grass_block**.

**Comment by RoboMWM** [comment]
Hmm, I'm guessing the grass caving in when disturbed is part of Additional Falling Blocks?

**Comment by RoboMWM** [comment]
Though you can add `GRASS_BLOCK` to the config, I don't know if it will work because it may not have an ID... since this is one of the many classes that uses that abstracted BlockType class which is backed by an int id.

**Comment by RoboMWM** [comment]
If this is the case, then probably just best to link to issue 128 and close, since it has to do with the underlying abstracted BlockType it's using instead of the feature itself.

**Comment by SlimeDog** [comment]
> Hmm, I'm guessing the grass caving in when disturbed is part of Additional Falling Blocks?

I think so. Whatever you think is best resolution. I'm just reporting what I find. :)

**Comment by RoboMWM** [comment]
I'm going to guess that adding `GRASS_BLOCK` to the config doesn't work since the material name was renamed and thus CB likely did not migrate its integer id.

**Comment by SlimeDog** [comment]
> I'm going to guess that adding `GRASS_BLOCK` to the config doesn't work since the material name was renamed and thus CB likely did not migrate its integer id.

Actually, that works just fine. Easy-peasy.

**Comment by RoboMWM** [comment]
Cool. I guess that'll solve any other issues that relate to GRASS_BLOCK and similar.
