### ISSUE TITLE
Torch mechanics testing

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#131]
Spigot 1.13.1 latest
EHM 1.13-alpha

The following torch mechanics are enabled on my servers:
1. Torches cannot be placed on dirt or grass.
2. Torches cannot be placed below Y=30.
3. Rain will extinguish unprotected torches.

Test results:
1. **PARTIAL FAIL**: Torches cannot be placed on top of dirt or grass (or sand). Torches can be placed on the side of any of those blocks.
2. **FAIL**: Torches can be placed below Y=30.
3. **FAIL**: Rain does not extinguish exposed torches.

**Comment by RoboMWM** [comment]
Exposed torches seem to be gradually removed over time while it is raining. It's only triggered when weather change changes to raining (i.e. if it's already raining in world on plugin load, it won't trigger).

Torch y level check also checks if the world environment is normal (overworld, vs. nether and the end).

For both cases, it seems there's a new Torch material - WALL_TORCH.

**Comment by SlimeDog** [comment]
That probably explains the torches placed on the sides of soft blocks: sand, dirt, etc.

**Comment by SlimeDog** [comment]
Spigot 1.13.1 latest
EHM 1.13-alpha-2

The following torch mechanics are configured on my servers:
```
    Torches:
      No Placement Under Y: 30
      No Placement On Soft Materials: true
      Rain Breaks Torches: true1.
```
"Soft Materials" are not defined in the configuration, but (IMHO) should include: coarse_dirt, dirt, grass_block, mycelium, podzol, sand, and soul_sand.

Test results in overworld:
- Confirmed: Torches cannot be placed on top or sides of any block below Y=30.
- Confirmed: Torches cannot be placed on top or sides of dirt, grass_block, or sand.
- Confirmed: Torches cannot be placed on sides of coarse_dirt, mycelium, podzol, or soul_sand.
- Confirmed: Torches on top and sides of blocks are broken probabilistically by rain.
- FAIL: Torches can be placed on top of coarse_dirt, mycelium, podzol, or soul_sand.
- FAIL: Torches cannot be place on sides of any blocks. Tested: stone, plank, wool. Torches can be placed on top of any of those blocks. This is probably a _torch_ vs _wall_torch_ issue.

Test results in nether:
- Confirmed: Torches cannot be placed on top of dirt, grass_block, or sand.
- FAIL: Torches can be placed on sides of dirt, grass_block, or sand.
- FAIL: Torches can be placed on top or sides of coarse_dirt, mycelium, podzol, or soul_sand.

NOTE: All results refer to survival mode. Torches can be placed on top or sides of any block in creative mode.

**Comment by RoboMWM** [comment]
Yea, soft materials are hardcoded. Probably can create a separate issue to make it configurable so someone can PR that.

**Comment by RoboMWM** [comment]
> FAIL[2]: Torches cannot be placed on sides of any blocks.

What's the message that prints for this? Don't see any reason why it'd deny for all blocks.

**Comment by RoboMWM** [comment]
This is really strange, I can attach torches to the east/west facing sides of blocks below the y value but not the north/south. Can you confirm?

**Comment by RoboMWM** [comment]
Should be fixed in alpha 4

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest
EHM 1.13-alpha3

In survival mode, I am able to place a torch on any surface of a stone block at Y=33. I am able to place a torch on any wall surface of a podzol block, but not the top.

(In creative mode, I am allowed to place torches, of course.)

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest
EHM 1.13-alpha4

Confirmed:
- Torches cannot be placed on any surface of farmland, but if the attempt is made on the sides, the torches are placed on top or sides of adjacent blocks at the Y value of the sides of the farmland block.
![untitled](https://user-images.githubusercontent.com/17748923/48154209-e1633f00-e27c-11e8-9d9a-8c2b575c0bc4.png)
![untitled](https://user-images.githubusercontent.com/17748923/48154865-7ca8e400-e27e-11e8-8064-67e2c889560a.png)

- Torches cannot be placed on any surface of any other soft blocks, at any Y value. Tested: course_dirt, dirt, mycelium, podzol, sand, soul_sand.
- Torches may be placed on any surface of hard blocks (except bottoms), above Y=30. Tested: stone.
- Torches cannot be placed on any surface of hard blocks, below Y=30. Tested: stone.

**Comment by RoboMWM** [comment]
Yes, this behavior is expected. The only other option is to wait a tick and make the torch pop off if it's attached to a "soft" material. See message in https://github.com/MLG-Fortress/ExtraHardMode/commit/31d56de3090066780782e59011b8dbb32c0084f0

In short, feature was added to mitigate "littering landscape with torches." So I'd expect these cases to be rare.

**Comment by RoboMWM** [comment]
This of course also allows mobs to spawn in these vanilla-generated landscapes since there's no light from easily-obtainable torches

**Comment by SlimeDog** [comment]
Note that the torches were attached to a soft material, just not the explicit target block. It seems to me that the torches attached to sand in the images above are not consistent with EHM. I agree that the instances are rare -- how often to you see farmland with side-adjacent air? I had to manufacture those test scenarios -- but it should not be allowed.

**Comment by SlimeDog** [comment]
> This of course also allows mobs to spawn in these vanilla-generated landscapes since there's no light from easily-obtainable torches

Yes. According to EHM documentation, one has to place glowstone or fire for light at Y<30. This is just one more hardening feature.
