### ISSUE TITLE
Crops death

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#143]
Spigot 1.13.2 latest
EHM 3.13.beta (second release)

I have three farm plots near the world spawn. Until recently, the crops never died, but at least once since 3.13.alpha3, crops died and changed to dead bushes (I do not know the release in which it occurred). 

Test method: I have a skript that replaces dirt with farmland, and replaces dead bushes with appropriate crops. Since running the skript, I have waited IRL hours for more crop death. No crops have been replaced. I have been logged on the entire period, in the relevant chunks, although occasionally I slipped into AFK.

What is the algorithm and cycle for crop death?

config.yml (business bits)
```
ExtraHardMode:
...
  Farming:
    Weak Crops:
      Enable: true
      Loss Rate: 25
 ...
```

**Comment by RoboMWM** [comment]
It checks every time a block grows from what I recall

**Comment by SlimeDog** [comment]
Hmmm. Within what radius? Since all of these crops are fully mature, there will be no local growth. It might be better on an occasional timer.

I'll set some to a lesser maturity and report back.

**Comment by RoboMWM** [comment]
It's for that specific block. It determines if it should die when that block grows.

Before it used to do it ~data value 7, which is about when crops would mature. But since other crops mature a lot sooner (data value 3) I moved it to greater than or equal to 2.

**Comment by SlimeDog** [comment]
The growing crops were affected. Adjacent fully-mature crops were not (consistent with ^^^).

In 1.12.2 versions, fully-mature crops were affected.

**Comment by RoboMWM** [comment]
https://github.com/MLG-Fortress/ExtraHardMode/blob/af6d56d81da8eb3e4b08f31576b6adb2dd586642/src/main/java/com/extrahardmode/features/AntiFarming.java#L179-L193

Which calls

https://github.com/MLG-Fortress/ExtraHardMode/blob/af6d56d81da8eb3e4b08f31576b6adb2dd586642/src/main/java/com/extrahardmode/module/BlockModule.java#L193-L259

Not sure what you mean by in 1.12.2 that fully-mature crops (assuming we're talking about wheat crops) were affected - it _only_ occurred to crops growing to full maturity (if they were already mature, no BlockGrowEvent is called on them).

**Comment by SlimeDog** [comment]
Hmmm. Looking at 1.12.2 test server...

**Comment by RoboMWM** [comment]
As for the original issue - what is the expected result? It seems your skript is replacing the dead bushes or something...? Not sure what the result should be.

**Comment by SlimeDog** [comment]
My skript is replacing the dead bushes on demand, for testing purposes. In production, they are left to player manipulation.

The desired result (for me) is that fully-matured crops are targeted for death. So I guess that is a feature request.

**Comment by RoboMWM** [comment]
Feature request... as in for crops that are fully matured, repeatedly test if they should die over time?

**Comment by RoboMWM** [comment]
Ok I'm not sure what you're asking for now.

Do you want the crop death check to occur on the respective block's final growth phase (so each crop has an equal chance of dying no matter its type) or all the time based on a fixed time interval for all crops in loaded chunks?

**Comment by SlimeDog** [comment]
I apologize for being unclear. I was exploring/considering the consequences of the various options, not deciding on one, assuming we were in a conversation.

My preference would be to provide three options:

1. Check at only the final growth change. That gives each plant one change to die through its growth cycle. It is equivalent to the 1.12.x behavior with the exception of beetroot, which never died since it never made the transition from age=6 to age=7. Consequently, beetroot must be implemented as an exception, to account for its different maturity age.
1. Check at every growth change. This means that carrots, potatoes, and wheat are more likely to die than beetroot, which is not ideal. It is a little harder to explain, but (probably) easiest to implement.
1. Check periodically. The negative of the first two options is that crops never die once mature. The beauty of this option is that crops are always at hazard, regardless of their growth status.

I suppose (1) should be the default, since it is consistent with the 1.12.behavior. Personally, I would configure a combination of (2) and (3), so that seedings are at some risk, but mature plants are also at risk.

The configuration to allow all three would look something like:
```
  Farming:
    # Convert crops to dead bushes and farmland to dirt, based on growth stage or a periodic timer.
    Weak Crops:
      # Final growth stage only
      # If this check is enabled, each seedling will have one chance to die.
      # Mature plants will never die.
      # This is the default.
      Kill Plants At Final Growth Stage:
        Enable: true
        Loss Rate Percentage: 21
      # If this check is enabled, seedlings will have 7 chances to die before maturity,
      # except beetroot seedlings will have only 3 chances to die before maturity.
      # The loss rate should be 1/7 of the final stage loss rate.
      # Mature plants will never die.
      Kill Plants At Any Growth Stage:
        Enable: false
        Loss Rate Percentage: 3
      # If this check is enabled, each plant will have many chances to die, even after maturity.
      # Consequently, the period should be infrequent and the loss rate should be very small.
      Kill Plants Periodically:
        Enable: false
        Period In Minutes: 10
        Loss Rate Percentage: 1
```

**Comment by RoboMWM** [comment]
Yea, it's fine to discuss the consequences too. Just didn't know which one you preferred c:

I think it'll be easiest if I provide a config option to specify which "mode" since it wouldn't make too much sense (IMO) to have all three or any combination enabled. Could be something like mode 1, 2 or 3 or could be a string identifier such as `crop death occurs at: "maturity" "growth" "anytime"`. Thoughts?

**Comment by SlimeDog** [comment]
Considering ^^ further, I think you are right, and that I would just use (3), which puts seedlings, young plants, and mature plants at risk. So please give it a go. Note that "anytime" will require a period specification, while the others will not.

I look forward to it.

**Comment by RoboMWM** [comment]
Well anytime would require a lot of work, since it can't just listen to an event, but has to be a task continually checking blocks in loaded chunks.

If you want you can add an issue for that 3rd option. (And another for the 2nd, if you'd like.) In the meantime I'll fix properly for original behavior (evaluation on block growth).

**Comment by SlimeDog** [comment]
Clarifying: You are implementing check on maturity (6->7 except 2->3 for beetroot)? Or check on any growth?
