### ISSUE TITLE
Endermen not teleporting players

### ISSUE THREAD

**Issue by SaganWolfric** [MLG-Fortress/ExtraHardMode#152]
It seems Issue #28 is back. Endermen are not teleporting players at all. I've tried multiple circumstances, including creating a 3 blocks high roof . Maybe there is a required change from 1.13 that has gone unnoticed regarding this feature?

Edit: I'm running the latest release of EHM with the latest Paper version.

**Comment by RoboMWM** [comment]
Can you run the eventdebug plugin and see if the EntityTeleportEvent fires when enderman teleport?

**Comment by RoboMWM** [comment]
Based on a recently reported and solved issue, Enderman teleporation is working just fine. Let me know here otherwise if not, with output of `/version` and `/version ExtraHardMode`
