### ISSUE TITLE
Dirt and grass do not occasionate cave-ins (no gravity on the surroundings)

### ISSUE THREAD

**Issue by SaganWolfric** [MLG-Fortress/ExtraHardMode#155]
The effect seen on the showcase video at 2:48, which you can see here: https://www.youtube.com/watch?v=4rGkxLnKmn8&feature=youtu.be&t=168 does not happen under any circumstances. Even with the additional falling blocks enabled:
```
Additional Falling Blocks:
    Enable: true
    [...]
```
And all cave-in features toggled on, the effect seen on the video cannot be done. When a dirt block is broken in a cave entrance or cave ceiling, **only the block directly above the broken dirt falls**. The blocks are subject to gravity, but they don't make the surrounding blocks of the same sort to come falling as well.

> # Dirt and grass, which is often compacted into a solid mass in cavern ceilings and floors, will also come crashing down when disturbed.

I'm running latest EHM and Paper. Apologies for English mistakes.

**Comment by RoboMWM** [comment]
Can you provide a video or screenshots of what's happening on your end?

**Comment by RoboMWM** [comment]
Am assuming it's just grass blocks that are affected? If so then it should be fixed by now. Let me know here otherwise.
