### ISSUE TITLE
Torch placement on soft materials can be bypassed with grass

### ISSUE THREAD

**Issue by SaganWolfric** [MLG-Fortress/ExtraHardMode#156]
Latest EHM
Latest Paper

Players can place torches directly on grass in order to bypass the soft materials restriction.

![2018-12-23_10 50 16](https://user-images.githubusercontent.com/32747488/50383742-f109dc00-06a0-11e9-9e2a-2a58473a2e17.png)
![2018-12-23_10 50 31](https://user-images.githubusercontent.com/32747488/50383751-f535f980-06a0-11e9-9453-b27efa307c9d.png)
![2018-12-23_10 50 45](https://user-images.githubusercontent.com/32747488/50383752-f6ffbd00-06a0-11e9-9b87-f0b2f51eef99.png)

**Comment by RoboMWM** [comment]
Just an FYI, "latest" isn't a version.

Idk if grass is considered a soft material.

**Comment by RoboMWM** [comment]
Ok I think that "grass" is what's missing from soft materials, since you normally can't place blocks on top of such blocks. (Whereas "Grass_Block" is on the list.)

Will add.

**Comment by RoboMWM** [comment]
According to #195 (though still pending `/version` and `/version ExtraHardMode` output) this issue still hasn't been fixed, unless tall grass is a different material than what's depicted here.
