### ISSUE TITLE
isolate the enivornment damage

### ISSUE THREAD

**Issue by zQuark** [MLG-Fortress/ExtraHardMode#158]
I need help isolating the environmental damage part as I have no idea how to deal with the source. I wanted to run the complete plugin, but it caused terrible stuttering on my server so I started replacing most of the features with other plugin configurations I run anyways, but  I am still missing the deadly-high enivorenment damage, especially lava and falling. So I want to have only the environment part of the code as a plugin to avoid the stuttering.

Any help would be much appreciated!

**Comment by RoboMWM** [comment]
Please provide a `/timings paste`

**Comment by zQuark** [comment]
Hey, sorry for the late response, I wasn't loaded for such a quick response. I updated some of my plugins and now it seems to go smoother.

Thanks for the quick answer anyhow, but I'd still love to see a more effective disabling of chosen components, if that would be possible in any way.

**Comment by RoboMWM** [comment]
Without `/timings paste` there's no reasonable place to begin any optimizations.
