### ISSUE TITLE
Falling blocks that fail to turn solid do not disappear

### ISSUE THREAD

**Issue by Pilvinen** [MLG-Fortress/ExtraHardMode#16]
Using 1.9 quickfix.
Physics -> Makes explosions uber cool by throwing blocks up into the air bugs out  by leaving falling entities on the ground. They are not removed or turned into solid blocks.

**Comment by RoboMWM** [comment]
Interesting, don't recall seeing the hotfix changing anything for that. Could you show me a video/screenshot of this?

**Comment by Pilvinen** [comment]
Here in this image you can see how my head is inside the block-entity that the explosion has thrown. I placed another, solid, cobble slab above it so you can see the difference.

http://snag.gy/hRuIK.jpg

**Comment by RoboMWM** [comment]
Hmm, does this only happen when it attempts to land on/near fence posts? Is this area protected by any area-protection plugins?

**Comment by Pilvinen** [comment]
Actually, now that I think of it. There is small spawn point protected by WorldGuard where this happened. And it happens not only with fence posts but everywhere in that area.

After I noticed it I disabled the block physics. I haven't tested if it happens elsewhere, but I will try it now.

**Comment by Pilvinen** [comment]
All right, I tested it. It seems like you correctly assumed that it only happens on WG protected regions where block placing has been denied.

Still a problem with the block entities that don't disappear but certainly not such a big issue as I first assumed since it only happens at the border of protected regions where you get blocks flying inside the protected region.

There is no simple way to remove those blocks. They will sit there through server restarts.

**Comment by RoboMWM** [comment]
I have an idea to fix, will probably use a scheduler to remove any block entities some time after an explosion. Obviously, WorldGuard is preventing placement of the block whereas normally it'd be removed after it lands. However, it is interesting to note that they remain until server restart - do they disappear if a client reconnects?

**Comment by Pilvinen** [comment]
No, they seem to be there permanently.

**Comment by Pilvinen** [comment]
I also noticed today that blocks that fall on fence posts will hover and bounce above the fence as entities. The area does not have WG protection.

**Comment by RoboMWM** [comment]
Is there already a block on top of the fence post? Is it on the side or on top of the fence post?

**Comment by Pilvinen** [comment]
1) Place fence
2) Place falling block ~5 blocks above it.
3) Watch it fall
4) It falls and finally stays above the fence, bouncing.

It doesn't disappear until you break the fence.

**Comment by RoboMWM** [comment]
Do you have `MORE_FALLING_BLOCKS_BREAK_TORCHES` enabled?

**Comment by Pilvinen** [comment]
Toggling MORE_FALLING_BLOCKS_BREAK_TORCHES to false fixes the issue.

**Comment by RoboMWM** [comment]
Alright, so it's a bug in that logic then, thanks for testing. Will push out a fix soon.

**Comment by RoboMWM** [comment]
Seems like the Paper team fixed this issue - turns out it's partly due to a bug in vanilla. https://github.com/PaperMC/Paper/blob/c1641b8e0cfaed3e3ff3907d6e78f0952e424c7f/Spigot-Server-Patches/0143-Fix-FallingBlocks-being-stuck-on-fences.patch
