### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by zQuark** [MLG-Fortress/ExtraHardMode#160]
When using the "Loose Items On Death - Tools exception" and adding Armor to the Tools list (Like diamond_helmet) the item will duplicate on death if there are more than one of the item in the player's inventory on death

**Comment by RoboMWM** [comment]
How does it duplicate? In player's inventory, or is it also dropped? Perhaps other keepinv-esque plugins may be causing this?

**Comment by zQuark** [comment]
Well I use MassiveCombat in terms of keepinventory, but it should only apply if you have a PvP flag.

The duplication happens when the item is dropped on death, then there is an actual stack (they stack on each other) on the floor, which is then also picked up as stack in addition to the other items that already existed.

I already set the oversized-stacksize of essentials to one to stop such non-stackables vom stacking, but it still happens.

**Comment by RoboMWM** [comment]
Ah, massivecore has a history of interfering with plugins (e.g. it used to screw around with the maxHealth player attribute on respawn). It does way too much stuff that it shouldn't be doing. Try testing without it.

**Comment by RoboMWM** [comment]
Or better yet try testing with just EHM installed.

**Comment by RoboMWM** [comment]
Going to assume this is a MassiveCore conflict. Let me know otherwise.
