### ISSUE TITLE
burning blindness

### ISSUE THREAD

**Issue by kuncoft** [MLG-Fortress/ExtraHardMode#161]
I have fresh spigot build 2059 without any other plugins and burning don't add blindness to player. It just add icon of blindness, but vision is normal. I tried to adjust duration up to 200 ticks, but it doesnt matter, no more manipulation were done with config, I tried to complete reinstall server/plugin. Version of extra hard mode is latest from official spigot page of the plugin - 3.13.1-59445b0. 

/version (img) https://i.gyazo.com/fe1a0ea1fb52ae94b945ed324bef0090.png

**Comment by RoboMWM** [comment]
Still should paste config anyways, you may have changed something and not know about it.
    ``` 
    paste the config inside backticks
    ````

**Comment by RoboMWM** [comment]
Also missing output of /version extrahardmode

**Comment by kuncoft** [comment]
https://ufile.io/hyide config
/version extrahardmode 

https://i.gyazo.com/3b8dbb6a20f933a7a0b1bd9223f3aa48.png /version extrahardmode

**Comment by RoboMWM** [comment]
just paste the config here, or in gist.github.com. Not that file downloader junk.

**Comment by RoboMWM** [comment]
Can you paste in http://gist.github.com or directly here in a comment? Makes it 500% more likely I'm going to revisit this issue sooner.

**Comment by RoboMWM** [comment]
Link has expired, so yea, definitely need a paste.

**Comment by RoboMWM** [comment]
Seems blindness was once a hardcoded potion effect for burning and was later removed (by Diemex when he still maintained it). However it's still applying the potion effect as per the config...

https://github.com/MLG-Fortress/ExtraHardMode/blob/8dd68580f73a4a3dd9f9a36e517f2961c6f75df3/src/main/java/com/extrahardmode/features/Players.java#L275-277

**Comment by RoboMWM** [comment]
I'm going to guess it's incorrectly placed in the config. Perhaps the default config is incorrect, if you're using that - but we won't know until we can get a snippet of that config in here.
