### ISSUE TITLE
Mobs not spawning on surface?

### ISSUE THREAD

**Issue by PsychoLynx** [MLG-Fortress/ExtraHardMode#163]
Howdy again!

I recently started a new world on Multiverse on our test server to restart our survival test - one of the first things I noticed was the lack of mobs on the surface of the Overworld and I have since then managed to narrow down the reason to EHM.

To confirm that EHM was the cause I made an absolutely clean test server - downloaded the latest Paper, latest EHM from SpigotMC, latest dev version of EssentialsX and latest Plugman as the only plugins on the server. The only things I changed in the server configs were the mob cap (70->140), difficulty 1 -> 3 and server seed. I also made myself the OP. I did not touch any of the plugin configs.

Surface with EHM on after butchering all mobs.
![surfacewithehm](https://user-images.githubusercontent.com/8504861/51785196-d2de4280-215c-11e9-8cfa-6de67294f299.png)

Surface after disabling EHM and butchering all mobs.
![surfacewithoutehm](https://user-images.githubusercontent.com/8504861/51785195-d245ac00-215c-11e9-95fb-8a4e525b349a.png)

Each time essentials reports that it butchered 140ish mobs, but in the case of EHM they seem to be packed underground(?). Only a few times have I seen surface mobs (mostly charged creepers, zombies, a single endermen) with EHM enabled.

I will also test this on the latest Spigot and report back.

**Comment by PsychoLynx** [comment]
Well, it seemed there was no difference between Paper / Spigot, however I found out where the mobs were 
![2019-01-26_11 32 29](https://user-images.githubusercontent.com/8504861/51785359-526d1100-215f-11e9-8409-c082db128555.png)

For whatever reason, they seem to have all spawned on the desert biome. Not sure what this means, but I would certainly appreciate a more vanilla distribution.

**Comment by RoboMWM** [comment]
Huh. Wondering if this has to do with the "spawn this mob instead if in this biome with configurable percentage" feature that was relatively-recently added.

**Comment by Bobbbe** [comment]
i have same problem ! 
CraftBukkit version git-Spigot-f56e2e7-9dc5658 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[ExtraHardMode] Enabling ExtraHardMode v3.13.1-59445b0

**Comment by RoboMWM** [comment]
Thanks for the info. This issue came in around one of the busiest moments of my life so I haven't been able to troubleshoot this. Could you guys try seeing if disabling options in the config (perhaps setting the spawn chance in biome setting to 0%) resolves this?

**Comment by Bobbbe** [comment]
for the moment, the tests I have done is to remove all the plugins from the server, I kept only, Vault, protocolib and pex (permissionsEx).
I'm looking for where I can change the percentage of appearance of 'Mobs' but I find nowhere this option!
Here is my configuration, if you can tell me the number of the line it would be simpler.
https://pastebin.com/3bCnuAjr

**Comment by PsychoLynx** [comment]
Upon further testing, the bug seems to be related to "Inhibit Monster Grinders: true" - when I switch this setting to false, the monsters begin spawning normally on the overworld.

**Comment by RoboMWM** [comment]
Ooh, thanks for that info psycholynx. Can you enable the debug config option?

**Comment by RoboMWM** [comment]
I'm thinking this might be a case of checking `grass` instead of `grass_block`

**Comment by RoboMWM** [comment]
Yup, that's the issue.

https://github.com/MLG-Fortress/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/module/BlockModule.java

On phone right now so will fix later.

**Comment by PsychoLynx** [comment]
Lovely! As for the debug, there seemed to be nothing special in there I got when flying around with the option enabled, sans messages about spider drops: https://pastebin.com/HkrR4v7h

I'll take the initiative to go check up on the animal limits bug with the debug on and see if I can't add to that.

**Comment by Bobbbe** [comment]
206/5000
actually, that solved the problem, thanks.
Now I do not know how to configure the gravity in the cave so that the 'dirt' falls! in the video we see the 'dirt' create a scree!
but, maybe it comes from the same problem with 'grass or grass_block'?
Because in this section I have not changed anything, everything is by default.

**Comment by Bobbbe** [comment]
for the moment :) i'm put Inhibit Monster Grinders: true when you update the plugin :)

**Comment by PsychoLynx** [comment]
Thank you kindly!
