### ISSUE TITLE
dragon defeat announcement

### ISSUE THREAD

**Issue by kuncoft** [MLG-Fortress/ExtraHardMode#166]
Hello, when player kill a ender_dragon, there is announcement in chat "The dragon has been defeated! (By:)" with no name of player.  There is just space. How I can fix this?

**Comment by RoboMWM** [comment]
How is it killed? By who? Do you have any plugins modifying damage?

IIRC it worked on my server so not sure what conditions would cause it to not attribute credit.

**Comment by RoboMWM** [comment]
I'm going to assume this is caused either due to plugin-created damage, or the players were somehow not in the end when it happened. Comment here if this is still an issue.
