### ISSUE TITLE
falling blocks don't seem to work

### ISSUE THREAD

**Issue by Pilvinen** [MLG-Fortress/ExtraHardMode#17]
I don't seem to be getting any block physics. Here is the relevant part from my config:

  Additional Falling Blocks:
    Enable: true
    Break Torches: true
    # Whether a falling block that is broken by an obstructing block should drop as an item
    Drop As Items: false
    # When a falling block lands it checks if the blocks around it should fall as well. Can cascade downwards infinitely.
    Landed Blocks Can Cause Blocks To Fall: true
    # Should a falling block damage players when it lands on them.
    Dmg Amount When Hitting Players: 2
    Turn Mycel/Grass To Dirt: true    
    Enabled Blocks:
    - GRASS
    - SMOOTH_BRICK@2
    - DIRT 
    - COBBLESTONE
    - MELON_BLOCK
    - HAY_BLOCK
    - COAL_BLOCK
    - MYCEL
    - SNOW
    - MOSSY_COBBLESTONE
    - SNOW_BLOCK
    - PUMPKIN
    - SOUL_SAND
    - '5882'
    - JACK_O_LANTERN

**Comment by RoboMWM** [comment]
> I don't seem to be getting any block physics. 

Elaborate - you mean when you place the block from the `Enabled Blocks` section with air underneath, it doesn't fall?

**Comment by Pilvinen** [comment]
Ah, sorry. It is working. It seems that if you have gm1 the blocks physics just don't kick in. With gm0 I'm getting block physics.

**Comment by RoboMWM** [comment]
Yea, you'll note at the top of the config whether EHM features are enabled for creative mode players (which defaults to true), as well as for ops (which defaults to false)
