### ISSUE TITLE
Have rain turn off campfires, like how it destroys torches.

### ISSUE THREAD

**Issue by manmadehuman** [MLG-Fortress/ExtraHardMode#178]
Title says it all. Rain should put out campfires.  
Thanks!

**Comment by RoboMWM** [comment]
Closed in https://github.com/MLG-Fortress/ExtraHardMode/commit/564b3acca0df2d3d8457a6425ad308c9577cdf4a

**Comment by DallasCarraher** [comment]
Just my 2 cents, I think campfires charged with hay perhaps shouldn't be put out? Just a thought.

**Comment by RoboMWM** [comment]
I agree that campfires should be treated a bit differently than torches. For now I could make the option default off, and if someone can think of better mechanics make a different issue and/or PR
