### ISSUE TITLE
Bad materials lists

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#182]
Spigot 1.14.3 (Jenkins 2395) git-Spigot-d05d3c1-087a2cf (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
ExtraHardMode 3.14.alpha-e859c88

Clean installation produced materials lists in _config.yml_ like
```
        Blocks (Block@id,id2):
        - !!org.bukkit.Material 'COAL_ORE'
        - !!org.bukkit.Material 'IRON_ORE'
        - !!org.bukkit.Material 'GOLD_ORE'
        - !!org.bukkit.Material 'LAPIS_ORE'
        - !!org.bukkit.Material 'REDSTONE_ORE'
        - !!org.bukkit.Material 'EMERALD_ORE'
        - !!org.bukkit.Material 'DIAMOND_ORE'
```
This cannot be read on server restart. Removing the "!!org.bukkit.Material " preceding the material names makes the configuration readable.

**Comment by RoboMWM** [comment]
Hmm, and it didn't do this before making the change that eliminated the "expected list<Material>" error?

**Comment by SlimeDog** [comment]
I don't know what that means. I haven't built a clean (ie., new) configuration in a while, and I jumped from 009e5c75 to e859c88.

**Comment by robinwezep** [comment]
Is there a quickfix available for this issue?

**Comment by SlimeDog** [comment]
> Is there a quickfix available for this issue?

Read back: _Removing the "!!org.bukkit.Material " makes the configuration readable._

**Comment by RoboMWM** [comment]
Hmm, note to self: Check where config is written to file, see if can exclude material_list (or convert to string list)

**Comment by robinwezep** [comment]
> > Is there a quickfix available for this issue?
> 
> Read back: _Removing the "!!org.bukkit.Material " preceding the material names makes the configuration readable._

I did that before i even read this page but i can still mine stone like i can in vanilla, no message whatsoever..

**Comment by SlimeDog** [comment]
All I did (above) was make the configuration readable. I didn't not test further. Thanks for the info.

**Comment by robinwezep** [comment]
Do you have any tips/hints to solve this one?

**Comment by SlimeDog** [comment]
Wait for RoboMWM to confirm the issue, then make a fix?

**Comment by RoboMWM** [comment]
The "inhibit stone mining" feature is disabled right now as I need to find a way to also pass in the values for how much damage a tool should incur for mining stone since the whole `material@data value` syntax is no longer valid as part of the refactor.

**Comment by robinwezep** [comment]
> The "inhibit stone mining" feature is disabled right now as I need to find a way to also pass in the values for how much damage a tool should incur for mining stone since the whole `material@data value` syntax is no longer valid as part of the refactor.

How long do you think this process will take?

**Comment by SlimeDog** [comment]
Well, there you have it. :)
Tips/hints: revert to 1.13.2 in production, which works very well. Reminder: 1.14.x is not production quality. YMMV.

**Comment by robinwezep** [comment]
> Well, there you have it. :)
> Tips/hints: revert to 1.13.2 in production, which works very well. Reminder: 1.14.x is not production quality. YMMV.

Still playing on 1.13.2 but im so excited to play this mod in 1.14.x

**Comment by RoboMWM** [comment]
Not to hijack this issue than it's already becoming but that _should_ be the only thing not functioning. If nothing else is then those are other issues you should file bug reports for.

Btw, you can file a bug report for that disabled feature anyways so I can update discussion on that. I was thinking of removing it temporarily since Idk demand for it (poll results are still a very small sample, only 20 or so responses).

**Comment by SlimeDog** [comment]
Another vote: Please restore stone mining. It's an important EH feature.

**Comment by RoboMWM** [comment]
Stone mining inhibitors will be restored, it's the damage to tools that idk about, at the moment.

**Comment by SlimeDog** [comment]
Right. Understood.

**Comment by RoboMWM** [comment]
Since I'm too lazy to make another issue and it was already brought up here... @robinwezep 

Restored the inhibit mining feature in https://github.com/MLG-Fortress/ExtraHardMode/commit/af17eb6abd41da3374781b328681b5d78b5030df

Please test: https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/builds/26454564/artifacts

If this feature is not working please make a new issue for it. Thank you!
