### ISSUE TITLE
1.14 compatibility / tracking

### ISSUE THREAD

**Issue by alexchandel** [MLG-Fortress/ExtraHardMode#184]
Four issues for 1.14 exist, all closed:

[x] #171
[x] #173
[x] #174
[x] #182

Other than unknown errors due to refactoring away BlockType entirely (#171), how much is left?

**Comment by RoboMWM** [comment]
No idea other than custom tool damage for breaking stone. Needs testing. I track via milestones, so if you want to do that please let me know.

**Comment by RoboMWM** [comment]
I.e. https://github.com/MLG-Fortress/ExtraHardMode/milestone/2
