### ISSUE TITLE
Wither skeletons not downing

### ISSUE THREAD

**Issue by Folas1337** [MLG-Fortress/ExtraHardMode#187]
Wither skeletons do not spawn with either the latest beta or stable build.

I tried it on a nether fortress on a test server with only this plugin. No wither skeletons after flying through two fortresses.

Disabled the plugin and killed all entities and it didn't even take 2 minutes to find several wither skeletons.

If you need more information, let me know.

**Comment by RoboMWM** [comment]
Did you try killing all entities and then rechecking before disabling the plugin?

**Comment by Folas1337** [comment]
Yes I did that twice and nothing showed up...

**Comment by RoboMWM** [comment]
Ok, try with antigrinder disabled.

**Comment by Folas1337** [comment]
I can pretty savely confirm that this option changes the behavior.
With "Inhibit Monster Grinders: false" they spawn just fine and with it set to true nothing seems to spawn.

Did you possibly forget nether bricks as a "natural spawn block" or something?

Hope that helps.

**Comment by RoboMWM** [comment]
Yea, I was looking at that. Thanks for testing.

Btw, as mentioned on spigot I never did say that this plugin doesn't mess with spawning mechanics. Just that more tests had to be conducted to verify.

**Comment by RoboMWM** [comment]
Nether bricks are included in natural spawn blocks for the nether. Hmm... 

https://github.com/MLG-Fortress/ExtraHardMode/blob/5c6d2615e1bf328217e22b20bd5402874e385988/src/main/java/com/extrahardmode/module/BlockModule.java#L436

**Comment by RoboMWM** [comment]
Hmm, there is NETHER_BRICK and NETHER_BRICKS...
