### ISSUE TITLE
Config options don't work

### ISSUE THREAD

**Issue by ivan-asenov** [MLG-Fortress/ExtraHardMode#192]
Yeah It's pretty self-explanatory - as far as I can tell (because explosions are messy) the following config options for TnT don't work:

      Enable Multiple Explosions: false  -  > Works, no extra explosions.
      # Change recipe to yield 3 tnt instead of 1
      Tnt Per Recipe: 1   - > I've tested it with 1 and it works, only gives 1
      Below Border:
        Explosion Power: 5   - > Not tested
        Set Fire: false   - > works, no fire but i didnt test if true gives fire
        World Damage: false   -  > Doesn't work, still damages world
      Above Border:
        Explosion Power: 0   - > Tested various powers, all seem the same so doesn't work
        Set Fire: false   - > Same as above
        World Damage: false   - > Same as above, doesn't work

I am using latest file from bukkit - 3.14.0-e490375, on latest paperspigot 1.14.4

**Comment by RoboMWM** [comment]
what
what happened here
