### ISSUE TITLE
Tools "stone count till break" from config is ignored.

### ISSUE THREAD

**Issue by IR0NSIGHT** [MLG-Fortress/ExtraHardMode#203]
No matter if i use 100 or 10000, it keeps breaking at the standard EHM limit (iirc 16)
i used 6000 before for iron and it worked fine, till i updated to the 1.14.4 version of EHM.

**Comment by RoboMWM** [comment]
idk what "1.14.4" version of EHM is.

idk what you mean by "standard EHM limit" of 16. You mean you can break 16 smooth stone before... what tool is broken?

**Comment by IR0NSIGHT** [comment]
Turns out its a problem with the server provider.
Mechanic works as intended on localhost with latest EHM and spigot versions.

**Comment by RoboMWM** [comment]
Provide output of `/version` and `/version ExtraHardMode` on the server-side, along with the config to help identify what's going on.
