### ISSUE TITLE
Feature Flag for sidebar helpertext

### ISSUE THREAD

**Issue by DallasCarraher** [MLG-Fortress/ExtraHardMode#206]
I noticed while playing that the native minecraft teams feature and sidebar are overridden by this plugin's sidebar helper text (i.e. notes about how zombies respawn). I was curious if we could put this helper text behind a feature flag in the yml? If you can point me to where this could be done (what files) I would be more than willing to create a PR. I would greatly appreciate if we could do this because this interference causes player name boxes to show above heads in my pvp server. Let me know :)

**Comment by RoboMWM** [comment]
This is in the config, you can change it to use chat instead. I believe this is what I do on my server for this very reason (and the fact that I have my own sidebar which I use as an on-screen menu).
