### ISSUE TITLE
Plugin forced player to join spectator mode

### ISSUE THREAD

**Issue by VenomHZ** [MLG-Fortress/ExtraHardMode#210]
when people died, this plugin forced people to join spectator or leave to title menu. When they join spectator mode and fly anywhere, they exit to title menu and return at the same spot to where the last position when they have spectator mode. I hope you can give me solution to disable joining spectator mode and just auto respawn.

**Comment by RoboMWM** [comment]
No, this plugin does not do that.

Vanilla Minecraft hardcore mode does that (never tried it myself). Disable that if you don't like that.
