### ISSUE TITLE
Can't translate the plugin into Russian

### ISSUE THREAD

**Issue by B3NR1** [MLG-Fortress/ExtraHardMode#211]
Every time I start a server with a new translation, it's fine at first, but when I restart the server or use the command '/EHM RELOAD', the translation breaks down and I have to restore it.
![Annotation 2020-03-04 210632](https://user-images.githubusercontent.com/24704968/75908902-12955480-5e5c-11ea-8d06-2d22475dbd40.png)
**sorry for my english :c**

**Comment by RoboMWM** [comment]
You'll need to force your server to use utf-8. It's a Java parameter which I've mentioned in another issue here. I'll find it when I'm not on a phone.
