### ISSUE TITLE
nned help, how do i increase stone allowed to mine with unbreaking

### ISSUE THREAD

**Issue by ImMetro** [MLG-Fortress/ExtraHardMode#212]

**Comment by RoboMWM** [comment]
wut

**Comment by ImMetro** [comment]
What i meant was iron can mine 32, diamond can mine 64 how can i increase this number with unbreaking because
IRON_PICKAXE#3 doesnt work

**Comment by RoboMWM** [comment]
Unsure if possible for config to determine enchants, sorry.

**Comment by RoboMWM** [comment]
this plugin's pretty old and probably never accounted for item enchants in that fashion? I could be wrong though.
