### ISSUE TITLE
RemoveExposedTorchesTask and MoreMonstersTask still appear in timings despite not being in use

### ISSUE THREAD

**Issue by PsychoLynx** [MLG-Fortress/ExtraHardMode#214]
Title. I don't use these things atm so I would rather they don't use my server's CPU!

**ExtraHardMode::Combined Totalcount(27)  total(21.84% 0.982s, 38.52% of tick)avg(36.38ms per - 19.26ms/0.53 per tick)**
* ExtraHardMode::Task: com.extrahardmode.task.RemoveExposedTorchesTask (Single)count(22)  total(21.84% 0.982s, 38.52% of tick)avg(44.65ms per - 19.26ms/0.43 per tick)
* ExtraHardMode::Task: com.extrahardmode.task.MoreMonstersTask (interval:600)count(5)  total(0.00% 0s, 0.00% of tick)avg(0.01ms per - 0.00ms/0.10 per tick)

Torches:
      # No placement of torches below Defined Value. Makes for scarier caves on the lower levels. Y: 0 to disable
      No Placement Under Y: 0
      # Soft materials include sand and dirt. Idea is that players don't litter the landscape with torches.
      No Placement On Soft Materials: false
      # When it rains there is a chance that torches will be removed in a chunk.
      # Any kind of block above the torch is enough to protect the torch
      Rain Breaks Torches: false
    Campfires:
      # When it rains there is a chance that campfires will be extinguished in a chunk.
      # Any kind of block above the campfire is enough to protect the campfire
      Rain Extinguishes Campfires: false

  General Monster Rules:
    # This is an advanced anti monster grinder module. It will block drops if the monster
    # spawned on an unnatural block, took too much damage from natural causes (falldmg etc.)
    # cant reach a player or can not easily reach a player e.g. monster is in water.
    Inhibit Monster Grinders: true
    More Monsters:
      Max Y: 0
      # A simple multiplier to increase spawns under ground by increasing the packspawning size.
      Multiplier: 1
    Monsters Spawn In Light:
      Max Y: 50
      # 0-3: bats spawning, 0-7 normal mob spawning, 8-11 mobs are hostile but don't burn, 12+ mobs burn
      Max Light: 7
      # Spawns monsters at locations where player has been previously.
      Percentage: 100

**Comment by RoboMWM** [comment]
Weren't you the one who requested Redstone torches to be covered by this task? Lol I'll take a look but I think that task also is responsible for also breaking crops when snowing - so you'd need to disable weak crops too if you don't want this task to do anything.

**Comment by PsychoLynx** [comment]
I honestly have no recollection! Either way, it's not like it's a massive loss of ticks, I'm just trying to make sense of my timings and thought it might not be intended (I don't have the expertise to look through the code, I'm afraid). Anyway, thank you ONCE AGAIN for your prompt response :)

**Comment by RoboMWM** [comment]
#32

**Comment by PsychoLynx** [comment]
Oh, alright. Guilty as charged then! You have a better memory than I do! (Although a lot has changed on the server in the past 4 years, so..)

**Comment by ItzDidoko** [comment]
Hey, I have the same problem! I don't have any redstone/normal torches in my world + I have disabled anything about this feature but it still takes 
![image](https://user-images.githubusercontent.com/36193824/85554604-bf732780-b62d-11ea-8f2a-6917424b75d3.png)
on average | all,
![image](https://user-images.githubusercontent.com/36193824/85554799-f0535c80-b62d-11ea-9002-610923585163.png)
on average | lag,
![image](https://user-images.githubusercontent.com/36193824/85554699-d6197e80-b62d-11ea-9eb2-4e6b1b8cfaf5.png)
on total | all and
![image](https://user-images.githubusercontent.com/36193824/85554897-095c0d80-b62e-11ea-8a57-08c597cd41ed.png)
on total | lag

This is like the heaviest idle thing on my server rn and I'm curious if there's a way to disable it. Thanks!

**Comment by RoboMWM** [comment]
please provide timings link

**Comment by RoboMWM** [comment]
and I'm sure you haven't disabled everything. You also have to disable weak crops. Please paste your config.

**Comment by RoboMWM** [comment]
As for MoreMonstersTask, it is checking all locations to see if the world has the threshold enabled - basically from the per-world config times. Eventually I want to reimplement that. So, hmm.

**Comment by RoboMWM** [comment]
rereading the reports you guys are showing, the impact is near-nil for MoreMonsters. Not much can be determined for RemoveExposedTorchesTask (which also is responsible for destroying weak crops) due to no timings links provided. Also, the resolution to avoiding this task being run has been provided (must disable both torches and weak crops).
