### ISSUE TITLE
Maven or Gradle？

### ISSUE THREAD

**Issue by LazyGon** [MLG-Fortress/ExtraHardMode#220]
Why does this project have both?
Very confusing.
I guessed this project is maintained with maven.
Let's delete gradle files.

**Comment by LazyGon** [comment]
Or If necessary, I will create PR about this issue.

**Comment by RoboMWM** [comment]
I use maven. Diemex converted this to gradle a while ago, and I left it there since it doesn't affect me using maven at all. But I guess I could rename it away or something if it's that confusing - just thought leaving it there would let people choose how they want to build.

**Comment by LazyGon** [comment]
I think if gradle files are left for people who use gradle, the build script should be also updated.
Build script for this project is outdated.

(In my personal opinion, you do not have to think about him because Diemex isn't active for 4 years. )

**Comment by RoboMWM** [comment]
Makes sense, if the build scripts no longer work then ya prolly makes sense to remove them then.
