### ISSUE TITLE
Standing on stone that changes to cobble causes suffocation damage.

### ISSUE THREAD

**Issue by LigerXT5** [MLG-Fortress/ExtraHardMode#23]
If player is standing on top of stone which turns to cobble, ex: mining ore, the player is killed. Due to player falling into hole when stone is replaced with cobble?

The only way I've been able to fix this, is to disable cobble from falling. Players were saying the cobble was bouncing when they changed, hence the idea of disabling of cobble.

**Comment by RoboMWM** [comment]
> cobble was bouncing when they changed

Bouncing?

**Comment by LigerXT5** [comment]
Changed meaning going from stone to cobble; replaced.
The bouncing, or hop, is what I've been told. I don't see it.

**Comment by RoboMWM** [comment]
>  Due to player falling into hole when stone is replaced with cobble?

I'm starting to suspect this is the case.

Two ways to get more info on this:

- [ ] using WorldEdit, replace a block below the stone block with a sign. Then break the ore in survival mode - see if the sign "breaks" the block or not.

- [ ] See does indeed fall down a bit while the block is turned to cobble and falling. Not sure how to get an objective test of this other than via video.

**Comment by RoboMWM** [comment]
Related: https://github.com/Di3mex/ExtraHardMode/issues/28

**Comment by RoboMWM** [comment]
Apparently craftbukkit spawns falling blocks half a block above. Due to [this commit](https://hub.spigotmc.org/stash/proj...mits/9ff3d7f51f2aafe98a95751caf0b7d5fc700db3e), blocks will no longer exhibit this behavior. As such, this should no longer be an issue.

**Comment by RoboMWM** [comment]
Let me know if this is still an issue.

**Comment by RoboMWM** [comment]
@LigerXT5 Can you see if this is still an issue? @retrontology claims it is despite the spigot changes mentioned in #49.

**Comment by LigerXT5** [comment]
I cannot say the issue is fixed, as I have not played MC Multiplayer in a year now. I apologize I cannot assist further.

**Comment by RoboMWM** [comment]
Finally discovered the reason - this feature (I'm guessing was added before the whole Environmental Injuries feature was added) is responsible as it was checking for any entities above or below the formed block. https://github.com/MLG-Fortress/ExtraHardMode/commit/f66a7e3e47c9f84facd17ba7e6d71650d120b385
