### ISSUE TITLE
Netherite Pickaxe cant break stone

### ISSUE THREAD

**Issue by Stealthy0** [MLG-Fortress/ExtraHardMode#235]
Netherite Pickaxe cant break stone it saying i need diamond pickaxe or iron pickaxe to mine it please fix

**Comment by RoboMWM** [comment]
I think you just need to add this to the config iirc.

Probably a very good idea to add this as a default entry.

**Comment by RoboMWM** [comment]
is 128 or 256 a good default?

**Comment by RoboMWM** [comment]
Had a short back and forth with the guy who bumped this (not OP), and adjusted defaults to be around half of the vanilla defaults - also added vanilla reference to config.
