### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by Tranqquil** [MLG-Fortress/ExtraHardMode#242]
I get the following message a few times per second.. 

[Fri, 7. Aug 2020 04:08:31 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d

How do I fix this? I have disabled most of the spawning mechanisms in extra hard mode but it doesn’t seem to help.

**Comment by RoboMWM** [comment]
You need to paste the whole stacktrace, but if you're using 1.16 you need to update the plugin to 3.14.2.

**Comment by Tranqquil** [comment]
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d
[Fri, 7. Aug 2020 08:24:37 MDT ERROR] Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d

This is the full thing. I am running on 1.15.2

**Comment by RoboMWM** [comment]
The full stacktrace does exist, you just need to find where it first appears the first couple of dozen times in your logs.

**Comment by RoboMWM** [comment]
Please also provide output of `/version`

**Comment by Tranqquil** [comment]
This server is running Paper version got-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) Checking version, please wait...
You are 13 version(s) behind.

**Comment by RoboMWM** [comment]
mk, I await your full stacktrace whenever you find it. Or, if you're having trouble going through your logs you can restart, reproduce, and get the stacktrace there.

**Comment by Tranqquil** [comment]
07.08 17:31:05 [Server] INFO at com.extrahardmode.features.monsters.Blazes.onEntitySpawn(Blazes.java:91) ~[?:?]
07.08 17:31:05 [Server] INFO java.lang.NoSuchFieldError: ZOMBIFIED_PIGLIN
07.08 17:31:05 [Server] ERROR Could not pass event CreatureSpawnEvent to ExtraHardMode v3.14.1-4693b7d

**Comment by RoboMWM** [comment]
oh 3.14 is what you want to use not 3.14.1. Thought I released 3.14.2 but that's not the case.

**Comment by Tranqquil** [comment]
so downgrading will fix this?
