### ISSUE TITLE
messages.yml get extreamly big with wrong charset?

### ISSUE THREAD

**Issue by misaka00251** [MLG-Fortress/ExtraHardMode#245]
I try to translate English to Chinese by manually edit the `message.yml`, but after a few reboots, the file got extremely big:

![image](https://user-images.githubusercontent.com/3908746/91038477-66c80700-e63d-11ea-8cd8-386b99dc1455.png)

And when I open it (hardly can...):

![image](https://user-images.githubusercontent.com/3908746/91038397-45671b00-e63d-11ea-9628-8e4578cd8280.png)

I can't scroll pass Line 34. Seems the charset is wrong.

**Comment by misaka00251** [comment]
Translate then save in UTF-8:

![image](https://user-images.githubusercontent.com/3908746/91039207-b65b0280-e63e-11ea-9a21-6e97c1b45a86.png)

After reboot the server:

![image](https://user-images.githubusercontent.com/3908746/91039191-ae9b5e00-e63e-11ea-85be-d37ff13278db.png)

**Comment by RoboMWM** [comment]
start your server with utf-8.

I'll dig up the command line argument.

**Comment by RoboMWM** [comment]
Add `-Dfile.encoding=UTF-8` to your start script.

**Comment by RoboMWM** [comment]
For reference, are you using Windows or Linux for your server?

**Comment by misaka00251** [comment]
I'm using Windows Server w/ Simp. Chinese locale.

`-Dfile.encoding=UTF-8` works, thank you!
