### ISSUE TITLE
Buckets of fish place water source blocks that do not evaporate.

### ISSUE THREAD

**Issue by QuantumToasted** [MLG-Fortress/ExtraHardMode#247]
A user on my server just discovered that buckets of fish (I assume any, tested with bucket of pufferfish) will place water source blocks that do not evaporate. Is this something that can be added in config or is this just a list of things that need to be added to the hard-coded list of items that place evaporating water sources?

EHM version: 3.14.1-4693b7d
Server version: 1.16.3 (Paper-204.jar)

**Comment by RoboMWM** [comment]
Should be fixed in 3.14.2, there was a PR on this already?

**Comment by RoboMWM** [comment]
ya, already fixed in 3.14.2, please update.
I think there's another PR pending with seagrass and kelp, idk if he also included dispenser.
