### ISSUE TITLE
Ghasts

### ISSUE THREAD

**Issue by 3Lord3** [MLG-Fortress/ExtraHardMode#259]
Ghasts:
    # Reduce the damage arrows do to Ghasts to make fights with Ghasts more challenging.
    Arrows Do % Damage: 20
This function does not work. The damage on the ghast does not change

**Comment by RoboMWM** [comment]
How are you verifying the damage amounts? Via a plugin debugging the health after the damage event?

**Comment by 3Lord3** [comment]
> How are you verifying the damage amounts? Via a plugin debugging the health after the damage event?

I tried changing the values to 100, 1 and 20. Each time the gust died from two arrows, no difference

**Comment by RoboMWM** [comment]
arrow damage varies depending on speed. I'll take a look, but very well could be another plugin modifying damage too, hence why I need exact values and also a test without other plugins. Also verify that EHM is enabled in that world.

**Comment by 3Lord3** [comment]
Oops, turns out that doesn't work in creativity. I checked it without operator rights, in creative. My mistake.

**Comment by RoboMWM** [comment]
Yup, EHM ignores settings for creative mode, or anyone with the exempt permission.
