### ISSUE TITLE
Mobs sometimes die spontaneously (at spawn time?)

### ISSUE THREAD

**Issue by tmewett** [MLG-Fortress/ExtraHardMode#264]
Sometimes as I'm traveling I find items dropped from animals just sitting around; raw beef, chicken, feathers, etc. Unless there's some mechanic I don't know about, with hostile mobs killing animals or something, I think something is going wrong with spawning.

The reason I think it's this plugin is that I once saw a group of pillagers where two of them were taking damage and died. This makes me think it could be a bug of the _Animal Overcrowding Control_ setting (currently 10). The others didn't actually move until I got quite close to them, so this is potentially interacting with the _entity-activation-range_ Spigot setting?

I haven't played Minecraft for a while so hopefully I've reported right and this isn't a bug or mechanic in vanilla

**Comment by RoboMWM** [comment]
`Animal Overcrowding Control` only affects `Animal`s and clears drops if an `Animal` dies due to this.

**Comment by RoboMWM** [comment]
there is a debug option you can enable, but other than that don't really know what else. include config and /version extrahardmode when you get more info.

**Comment by tmewett** [comment]
Ah ok, seems very unlikely it's this plugin then. My next culprit is the Modern Beta world-gen data pack, maybe that has defined the spawns weirdly. Thanks
