### ISSUE TITLE
Health not regenerating, food going down fast

### ISSUE THREAD

**Issue by narcarsiss** [MLG-Fortress/ExtraHardMode#27]
Hi.
Latest Version *.7.2 Health bars stay on 4 hears, and food bar goes down 1 1/2 and just stops there.

No other plugins besides swornRPG and Essentials.

I can provide more info if need be.

**Comment by RoboMWM** [comment]
Um, explain how to reproduce please.

You might also want to try without swornRPG if it does anything that deals with health, hunger, or regeneration.

**Comment by narcarsiss** [comment]
Solved. latest world guard defaulted to  "disable-regen-health: true"

Just so happens I updated both plugins at the same time.

**Comment by RoboMWM** [comment]
That's an odd thing to make default...
