### ISSUE TITLE
Enderman no longer teleports player

### ISSUE THREAD

**Issue by Vanmc** [MLG-Fortress/ExtraHardMode#28]
I'm using the latest release version 3.7.2.19 tested on Spigot 1.9.2 also tried "May Teleport Players: false" thinking it might be just flipped did not work also tried running only ehm still nothing. Either the percentage of an enderman teleport you to them is low or its broken. I also tried standing on a 1 by 3 block tried surrounded myself and still nothing. I don't see any errors in the consoles also

**Comment by RoboMWM** [comment]
I'm not sure what events trigger the Enderman teleport feature, though I think it happens when the Enderman is obstructed (I've only had an Enderman teleport me once when I trapped it via an element bending plugin I have installed). Can you reproduce situations in 1.8.8 where you'd be teleported?

**Comment by Vanmc** [comment]
1. tested with ExtraHardMode-3.6.7 with 1.8.8 spigot it worked

2. tested with ExtraHardMode-3.7.2 <-latest version with 1.8.8 spigot it produce an interesting error though http://pastebin.com/pSQT04A7

3. tested with ExtraHardMode-HotFix with 1.9.2 spigot did not work shows an error http://pastebin.com/RkqpFqbd

4. tested with ExtraHardMode-HotFix with 1.9 spigot produce an error on load about java.lang.NullPointerException of ArmorWeightTask still did not work

5. tested with ExtraHardMode-3.7 with 1.9 spigot produce an error on load about java.lang.NullPointerException of ArmorWeightTask  and similar error with (3) still did not work

I'll assume the ArmorWeightTask is likely fixed on the latest version since i don't see any error during start

**Comment by RoboMWM** [comment]
> 2.tested with ExtraHardMode-3.7.2 <-latest version with 1.8.8 spigot it produce an interesting error though http://pastebin.com/pSQT04A7

Ok, that confirms 3.7.2 (or any version of 3.7 iirc) to not be compatible with versions below 1.9. 1.9 changed the sounds enum, so that's what the error is about.

> 3.tested with ExtraHardMode-HotFix with 1.9.2 spigot did not work shows an error http://pastebin.com/RkqpFqbd

> 4.tested with ExtraHardMode-HotFix with 1.9 spigot produce an error on load about java.lang.NullPointerException of ArmorWeightTask still did not work


> 5.tested with ExtraHardMode-3.7 with 1.9 spigot produce an error on load about java.lang.NullPointerException of ArmorWeightTask and similar error with (3) still did not work

Unrelated error - plugin should work despite the armor weight feature not working. See #21 for details.

What was the situation that caused the Enderman to teleport you?

**Comment by Vanmc** [comment]
i just did what i posted on the very top i made a 1 by 3 block then around it is a square block with height of 1 by 3 i grabbed some enderman spawn the around me gamemode 0 myself and aggro them by either hitting or looking at them, i also tried just having 1 by 3 and did the same procedure i manage to get teleported also

**Comment by RoboMWM** [comment]
Ok, I was thinking something totally different, thanks for the video.

**Comment by RoboMWM** [comment]
Please test with this debug version (make sure to **rename .zip to .jar**
[ExtraHardMode.zip](https://github.com/MLG-Fortress/ExtraHardMode/files/206723/ExtraHardMode.zip)
)

Watch your server log for debug messages as you attempt to get Enderman to teleport you. There's three cases where teleporting can be denied, see the above commit for details.

**Comment by Vanmc** [comment]
Strangely enough i fail to even get a log as i tried to purposely be on water this is tested on spigot 1.9.2 with the debug version. I did noticed one thing though enderman acts like zombies than being enderman the aggro animation is gone they still do teleport to you though not the other way around.

https://youtu.be/hP2QoqDg74s

**Comment by RoboMWM** [comment]
Try this with more debug messages. Messages should now also be broadcast so you don't miss them, just in case. See https://github.com/MLG-Fortress/ExtraHardMode/commit/dc0c96dd55087a566fb82d9499afc76209979f1b for details.

[ExtraHardMode.zip](https://github.com/MLG-Fortress/ExtraHardMode/files/206985/ExtraHardMode.zip)

**Comment by Vanmc** [comment]
i lost it when with Bukkit.broadcastMessage("EHM: RANDOM HAZ BEEN REACHED"); XD 
sadly once again same version 1.9.2 spigot with this new debug version no debug not even a broadcast its like this part of class is not even called

**Comment by RoboMWM** [comment]
Alright, time to debug all the things.

[ExtraHardMode.zip](https://github.com/MLG-Fortress/ExtraHardMode/files/207305/ExtraHardMode.zip)

Ensure that `/version ExtraHardMode` prints 3.7.2-debug

**Comment by Vanmc** [comment]
Still nothing all those broadcast images don't see anything I tried updating my spigot even tried craftbukkit both 1.9.2 used the one you gave me above even checked the source code of the class to see I am using the right build 

http://i.imgur.com/wZmeEuU.png
http://i.imgur.com/nJm0jBT.png

**Comment by RoboMWM** [comment]
Seems to be a spigot/CB bug... https://hub.spigotmc.org/jira/browse/SPIGOT-1935

**Comment by RoboMWM** [comment]
Can you please update spigot to see if this works now (with or without debug version)?

https://hub.spigotmc.org/jenkins/view/All/job/CraftBukkit-RSS/407/changes#detail0

**Comment by Vanmc** [comment]
updated to the latest version its now working thanks!
