### ISSUE TITLE
Grifing by worldgurd/protectionstone 

### ISSUE THREAD

**Issue by Yusaki-Akito** [MLG-Fortress/ExtraHardMode#280]
I found this grifing by worldguard/protectionstone when snow on the crops

**Comment by RoboMWM** [comment]
wut

**Comment by Yusaki-Akito** [comment]
I don’t know but they said the plugin need to support worldguard and set “dont do that in my area”

**Comment by RoboMWM** [comment]
what is the issue?

oh you mean "griefing?"

Are you trying to say that snow damages crops in worldguard/protectionstone areas?

That is kinda the point of the plugin though, protect the crops by placing blocks above, or disable in the config.
