### ISSUE TITLE
1.18 Compatibility - Spider death below Y-0 cause a crash report

### ISSUE THREAD

**Issue by jumperdenfer** [MLG-Fortress/ExtraHardMode#295]
Hi,

Currently when a spider die below the Y-0, an error happen with a crash-report.
We probably can fixe this issue by changing the min Y to -126 in " Features > monsters > spiders.java at l.144 " 

In hope that can help you. 😀

**Comment by GiorgioBrux** [comment]
Why change it to -126 instead of -64?

**Comment by GlowPon3** [comment]
Might have to take a look at the maximum as will since world height increased.  Maybe not.
