### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by mihalera** [MLG-Fortress/ExtraHardMode#301]
Paper – git 132
Extra Hard Mode – 3.15.0
Log – https://mclo.gs/YQY8cNG

**Comment by GiorgioBrux** [comment]
This has already been fixed (albeit a release isn't available yet). #292

**Comment by mihalera** [comment]
Server on free hosting, Aternos. There will be no way to change.

**Comment by GiorgioBrux** [comment]
If you can't manually upload the latest artifact you'll need to wait until Robo pushes a release and aternos adds it to their systems sadly.

**Comment by alexchandel** [comment]
[The latest build artifact](https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/build/artifacts) works for me on PaperMC 1.18.1.  @RoboMWM We just need a release bump.

**Comment by mihalera** [comment]
Ok

**Comment by OhNo2** [comment]
The latest build artifact does not work for me on Purpur 1.18.1

**Comment by Remski01** [comment]
GiorgioBrux, could you update/reupload the build on the url above? (The build job does not contain any artifacts.) Thx :)

**Comment by RoboMWM** [comment]
I'll make a release
