### ISSUE TITLE
Player Death feature no longer works

### ISSUE THREAD

**Issue by Vanmc** [MLG-Fortress/ExtraHardMode#31]
I haven't tested so much yet so far I think gamerule feature of default minecraft simply overrides this feature.

**Comment by RoboMWM** [comment]
What feature? Can you explain what's supposed to happen?

**Comment by Vanmc** [comment]
With this Loose Items On Death Enable: true based on the description ain't it suppose to keep the items in the inventory and at same time removes some items based on the percentage or I am misunderstanding here. Because instead of that scenario whats happening is when I die, I lost my items then the percentage calculation then takes over. So I then thought it must have something to do with gamerule keepInventory so I made it true thinking it would keep my items then calculate the percentage that will be removed. But what I happen instead is it override EHM death feature and simply just kept the items in the inventory.

**Comment by RoboMWM** [comment]
I assume the feature removes it from your dropped loot...

**Comment by Vanmc** [comment]
Ah that kind of make sense now since ehm does not store any data at all.
I am really sorry for this commotion feel free to close this issue.

**Comment by RoboMWM** [comment]
I'm still not entirely sure what the issue or misunderstanding here is/was in the first place :S
