### ISSUE TITLE
Future Paper thing

### ISSUE THREAD

**Issue by Remski01** [MLG-Fortress/ExtraHardMode#311]
`[18:56:17 WARN]: @EventHandler method com.extrahardmode.features.AntiGrinder#onEntityDeath returns non-void type boolean. This is unsupported behavior and will no longer work in a future version of Paper. This should be reported to the developers of ExtraHardMode v3.15.0-e4f17b1 (RoboMWM,Diemex,Big_Scary)`

We are currently running `git-Paper-312 (MC: 1.18.2)`
(To note, its 21 builds outdated, but would guess they 1.19 and higher when released)

**Comment by RoboMWM** [comment]
why is this unsupported tho

**Comment by Remski01** [comment]
No idea, cant find anything about it.

**Comment by RoboMWM** [comment]
if someone can ask in their dumcord that'd be nice. I don't have a problem changing it, but I still want to know why tho.

**Comment by SlimeDog** [comment]
Duplicate of https://github.com/MLG-Fortress/ExtraHardMode/issues/303

**Comment by Remski01** [comment]
Ya, didnt saw that one. Oopsies

**Comment by RoboMWM** [comment]
Thank you SlimeDog, I've been slowly ploughing through all the stacked-up github notifications.

**Comment by SlimeDog** [comment]
Reminder that these are still reported by Paper 1.19.2.

**Comment by alexchandel** [comment]
> why is this unsupported tho

It's probably the wrong signature of the interface.  Interface implementations can't have arbitrary signatures.  This return type might've been an incorrect signature that "accidentally worked."

This is supposedly fixed by #316, however there is no release, and the CI build artifact is gone.

**Comment by alexchandel** [comment]
Note this is a dupe of #303 (closed).  @RoboMWM new release, please?

**Comment by RoboMWM** [comment]
I wanted to take this as an opportunity to use github releases, but alas I'm still behind on my list of priorities. I'll push out a manual release.

**Comment by RoboMWM** [comment]
Oh, I already pulled in something that made a new CI artifact. https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/builds/46609551/artifacts

**Comment by SlimeDog** [comment]
Looks good on Paper 1.19.4-501. Thanks.
