### ISSUE TITLE
Compatibility with CreeperHeal

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/ExtraHardMode#39]
Reported by [SpacePuppeh:](https://www.spigotmc.org/threads/extra-hard-mode.129354/#post-1515210)

> I had both EHM and CreeperHeal enabled, and CreeperHeal was not restoring a bunch of creepers I sent off for testing.

**Comment by RoboMWM** [comment]
EHM probably breaks blocks manually? https://github.com/Di3mex/ExtraHardMode/issues/10#issuecomment-31418027

**Comment by suburbannoize** [comment]
I'm trying to do the same thing, did you ever figure anything out?

**Comment by RoboMWM** [comment]
I asked @spacepuppeh for further info, but never got any. Try checking the thread and then comment here if you can add any information about what's exactly happening with what options.

**Comment by suburbannoize** [comment]
With all plugins active explosions work just fine but creeperheal doesn't heal
with just extrahardmode disabled creeperheal works perfectly.  

I have tried almost every option and many combinations but haven't come up with anything to grant permission to allow creeperheal to regenerate exploded areas.

**Comment by RoboMWM** [comment]
Does it heal some of the area? Thing is, creepers alone don't have any extra explosions like TNT does with EHM... I guess it's best to focus on one thing at a time.

So, creepers with power level 3 (idk if that's default, I think it is in config) aren't being restored at all with creeperheal? And does it fail to heal above and below sea level?

**Comment by RoboMWM** [comment]
Yea, this is an issue with CreeperHeal. It needs to monitor BlockExplodeEvent if it wants to track and replace exploded blocks from custom-created explosions.

**Comment by RoboMWM** [comment]
Fixed by creeperheal dev.
