### ISSUE TITLE
Need help - disable all the messages

### ISSUE THREAD

**Issue by Zomblad** [MLG-Fortress/ExtraHardMode#47]
Hello. Im trying to disable most of the messages from this plugin (like message about blaze spawning near bedrock, or disabled placing ores near stone). I dont understand how to disable them. Some of them can be disable, but some are still popping out while playing. I have added special permission but nothing happend (also I have turned every message to false in messages.yml). Help me please...

**Comment by RoboMWM** [comment]
Please paste/upload your messages.yml.

```
```yml
messages.yml file here...
```

**Comment by Zomblad** [comment]
[spoiler]####################################################################################################%n#                                  Messages sent by ExtraHardMode                                  #
#                       Messages are only sent for modules that are activated                      #
#                            Modes (has to match exactly, ignores case)                            #
#       Disabled: Message won't be sent even if feature that would sent the message is active      #
#                         One_Time: Will be sent to every player only once                         #
#            Notification: Gets sent every time with a timeout to prevent spamming chat            #
#             Tutorial: Sent a limited number of times and not displayed after 3 times             #
#         Broadcast: Shown to whole server. Only few messages make sense to be broadcasted         #
#                                            Variables:                                            #
#                  $ALLCAPS is a variable and will be filled in for some messages                  #
#                                     $PLAYER: Affected player                                     #
#                            $PLAYERS: If multiple players are affected                            #
#                             $DEATH_MSG: Death message if someone dies                            #
#                                       $ITEMS: a player lost                                      #
####################################################################################################
Messages:
  Display Messages In Scoreboard:
    Enable: false
    Scoreboard Title: '&cExtraHardMode'
    Remove All Color Codes: true
    Notification:
      Enable: false
      Displaytime In Ticks: 600
      Textcolor: NONE
    Tutorial:
      Enable: false
      Displaytime In Ticks: 1800
      Textcolor: NONE
    Broadcast:
      Enable: false
      Displaytime In Ticks: 1200
      Textcolor: NONE
  NoTorchesHere:
    Mode: notification
    Msg: There's not enough air flow down here for permanent flames. Use another method to light your way.
  StoneMiningHelp:
    Mode: notification
    Msg: You'll need an iron or diamond pickaxe to break stone.  Try exploring natural formations for exposed ore like coal, which softens stone around it when broken.
  NoPlacingOreAgainstStone:
    Mode: notification
    Msg: Sorry, you can't place ore next to stone.
  RealisticBuilding:
    Mode: notification
    Msg: You can't build while in the air.
  RealisticBuildingBeneath:
    Mode: notification
    Msg: You can't place a block directly beneath you.
  LimitedTorchPlacements:
    Mode: notification
    Msg: It's too soft there to fasten a torch.
  NoCraftingMelonSeeds:
    Mode: notification
    Msg: That appears to be seedless!
  LimitedEndBuilding:
    Mode: notification
    Msg: Sorry, building here is very limited.  You may only break blocks to reach ground level.
  DragonFountainTip:
    Mode: notification
    Msg: Congratulations on defeating the dragon!  If you can't reach the fountain to jump into the portal, throw an ender pearl at it.
  NoSwimmingInArmor:
    Mode: notification
    Msg: You're carrying too much weight to swim!
  DragonDefeated:
    Mode: broadcast
    Msg: 'The dragon has been defeated!  ( By: $PLAYERS )'
  PlayerKilledByDragon:
    Mode: broadcast
    Msg: $PLAYER was killed while fighting the dragon!
  PlayerChallengingDragon:
    Mode: broadcast
    Msg: $PLAYER is challenging the dragon!
  HorseFeedLow:
    Mode: notification
    Msg: You have saved your horse from starving, but it's still very hungry.
  HorseFeedMiddle:
    Mode: notification
    Msg: Your horse has ate well.
  HorseFeedHigh:
    Mode: notification
    Msg: Your horse is satiated.
  HorseStarveLow:
    Mode: notification
    Msg: Your horse is very tired and needs some food.
  HorseStarveMiddle:
    Mode: notification
    Msg: Your horse is about to starve.
  HorseStarveHigh:
    Mode: notification
    Msg: Your horse is starving, feed it or it will die.
  ChargedCreeper:
    Mode: tutorial
    Msg: Charged Creepers explode instantly when hit. Run!
  BlazeOverworld:
    Mode: tutorial
    Msg: Blazes spawn near lava and their fiery breath causes a big explosion on death!
  BlazeNether:
    Mode: tutorial
    Msg: Blazes spawn everywhere in the Nether and may split on death!
  Magmacube:
    Mode: tutorial
    Msg: These small buggers actually are just disguised blazes!
  Ghast:
    Mode: tutorial
    Msg: These fearsome Ghasts wear invisible arrow deflective armor! Ghasts drop a lot more loot as well.
  PigZombieAlwaysAngry:
    Mode: tutorial
    Msg: RUN! Pig Zombies are always angry and hungry!
  PigZombieDropNetherwart:
    Mode: tutorial
    Msg: You can get netherwart from slaying Pig Zombies
  ZombieRespawn:
    Mode: tutorial
    Msg: Zombies might resurrect if not on fire!
  ZombieSlowPlayer:
    Mode: tutorial
    Msg: Zombies slow you down when hit!
  SkeletonDeflectArrows:
    Mode: tutorial
    Msg: Arrows just pass through Skeletons, you gotta go close combat!
  EndermanGeneral:
    Mode: tutorial
    Msg: Enderman can teleport you too!
  CreeperDropTnt:
    Mode: tutorial
    Msg: Creepers may drop activated tnt on death!
  ExtinguishFire:
    Mode: tutorial
    Msg: Putting out fire with your hand will catch you on fire.
  ListLostItemsOnDeath:
    Mode: notification
    Msg: §8§l [§4☣§8§l] §6§l§oНекоторые вещи были потеряны §8§l[§4☣§8§l]
  InformPlayerOnLostItems:
    Mode: tutorial
    Msg: On death there is a a chance you might lose some of your items!
  BucketFill:
    Mode: tutorial
    Msg: You can pick up water, but once you place it, it evaporates. Get some ice if you want to farm!
  AntifarmingUnwatered:
    Mode: tutorial
    Msg: Your crops need sufficient water, otherwise they'll dry out!
  AntifarmingNotEnoughLight:
    Mode: tutorial
    Msg: Your crops require natural light to grow!
  AntifarmingDesert:
    Mode: tutorial
    Msg: Deserts are really dry and nothing grows here!
  AnimalOverCrowd:
    Mode: tutorial
    Msg: Animals need space! Consider putting them in a bigger area
  NetherWarning:
    Mode: tutorial
    Msg: This is a dangerous place. Make sure you come prepared with arrows and good gear.
[/spoiler]

**Comment by Zomblad** [comment]
so?
what did I do wrong?

**Comment by RoboMWM** [comment]
Try making these strings empty, e.g.:

```yml
  Msg: ''
```

I'm not sure if disabling categories of messages are respected when not using the scoreboard.

**Comment by Zomblad** [comment]
But what can I do in msg's with out " "?

**Comment by Zomblad** [comment]
like 
There's not enough air flow down here for permanent flames. Use another method to light your way.

**Comment by Zomblad** [comment]
never mind, but im got now this thing: 
![2016-06-08_20 07 36](https://cloud.githubusercontent.com/assets/6556646/15903305/c469961c-2db4-11e6-964b-365ff65ae129.png)

**Comment by Zomblad** [comment]
So, any other ways to disable that? Because its a little bit annoying of getting empty messages.

**Comment by RoboMWM** [comment]
Yes I'll have it not send anything when message is empty, my time is limited between Mon-Thurs though. I'll get to it, I've labeled it as such.

**Comment by Zomblad** [comment]
Okay! Awesome, I will wait for it.

**Comment by RoboMWM** [comment]
As mentioned in the commit above I've added this 2 days ago. Here's a compiled jar: https://github.com/MLG-Fortress/ExtraHardMode/releases/tag/3.8.5

**Comment by Zomblad** [comment]
Thank you very much! :)
