### ISSUE TITLE
Falling blocks are very buggy

### ISSUE THREAD

**Issue by Pilvinen** [MLG-Fortress/ExtraHardMode#49]
Video showing the bug below. Notice the displacement of the falling block. And also notice in the second tree on the video how the displacement of the falling blocks inside the tree leaves makes blocks above the broken block disappear, *poof*.

https://www.youtube.com/watch?v=6WV7kTkBB1I

Spigot 1.10.2
EHM 3.8.5

**Comment by RoboMWM** [comment]
Very likely to be a spigot bug, a similar problem is being discussed here: https://www.spigotmc.org/threads/gravitree-prevent-floating-treetop-eyesores-paid.90058/page-7

**Comment by RoboMWM** [comment]
Aha, this is why!

https://hub.spigotmc.org/stash/proj...mits/9ff3d7f51f2aafe98a95751caf0b7d5fc700db3e

Prompted by this ticket: https://hub.spigotmc.org/jira/browse/SPIGOT-2548
