### ISSUE TITLE
Farming limitations don't affect beetroot

### ISSUE THREAD

**Issue by PsychoLynx** [MLG-Fortress/ExtraHardMode#52]
Hey there!

We're running EHM 3.8.5 - I just noticed that beetroot plants don't seem to be affected by being in the desert (unlike wheat for example, which dies normally), nor do any of them die despite a configured chance of 25%.

Thanks for your time!

**Comment by RoboMWM** [comment]
Beetroot is a new plant (added in 1.9?) and as such will need to be added as a "plant" block or whatever. Thanks for the report, hopefully I'll get some time to look into this within a couple weeks.

**Comment by RoboMWM** [comment]
Btw can you confirm if this is fixed? https://www.spigotmc.org/threads/extra-hard-mode.129354/page-8#post-2165460 indicates otherwise..

**Comment by PsychoLynx** [comment]
Can confirm, not fixed :/ Probably should have caught it earlier.

**Comment by PsychoLynx** [comment]
Thank you kindly <3

**Comment by SlimeDog** [comment]
Spigot 1.11.2 latest
EHM 3.11

I have beets planted in a village-style planter, but outside the range that the villagers seem to notice. Some of the beet plants become potato plants, but none become sticks. They are in a Factions safezone; could that be a factor?

**Comment by RoboMWM** [comment]
Can you confirm again @PsychoLynx ?

**Comment by PsychoLynx** [comment]
@RoboMWM I'm embarrassed to admit that the bug is actually not fixed, in 3.11 I just received no further reports from players so I thought it had been - but after setting weak crops to 99%, beets are still growing strong unlike other crops. Have not been able to replicate the potato problem though! (Although I didn't try growing crops near a village)

**Comment by RoboMWM** [comment]
Hmm, `newDataValue.getData() >= 7` - My guess is that beetroot doesn't need to get to data value 7 to consider it grown or not.

**Comment by RoboMWM** [comment]
Yup, thanks for confirming. Now this'll be part of the fun with 1.13 yay...

**Comment by RoboMWM** [comment]
Fixed in https://github.com/MLG-Fortress/ExtraHardMode/commit/af6d56d81da8eb3e4b08f31576b6adb2dd586642
