### ISSUE TITLE
When leaving the world with this enabled i remain heavy until logout/in

### ISSUE THREAD

**Issue by krustymk** [MLG-Fortress/ExtraHardMode#55]
Ive set up a portal system to tp to/from the enabled world
Also had some 'zero's' over several tools back in the normal world which disappeared as soon as i selected them.
Thanks for taking the time to keep this going :)

**Comment by RoboMWM** [comment]
> Also had some 'zero's' over several tools back in the normal world which disappeared as soon as i selected them.

Should be put in a separate issue (this is likely due to the "damage tools on death" feature)

Could you also paste output of `/version` and `/version ExtraHardMode`

I'm semi-aware that this is an issue (I've observed it on my server).

**Comment by krustymk** [comment]
This server is running CraftBukkit version git-Spigot-f9671b8-4d87c34 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Checking version, please wait...
19:17:04You are 2 version(s) behind

ExtraHardMode version 3.8.6

Thanks

**Comment by RoboMWM** [comment]
(Note to self/potential people that want to PR):
Easiest way to fix is simply watch PlayerChangeWorldEvent, and set speed if armorweight checking is disabled in destination world.

**Comment by krustymk** [comment]
No worries, it only happened the once and to me.. so may be something to do with being op?
Ill keep an eye out
Thanks

**Comment by krustymk** [comment]
Top man!
Thanks
