### ISSUE TITLE
Bug: spruce logs not falling

### ISSUE THREAD

**Issue by Zomblad** [MLG-Fortress/ExtraHardMode#56]
Hello. I found a bug in version 3.8.4 of EHM. Spruce trees are not falling down like other. FIx this please, because its annoying to make a ladders for every tree to cut it at 100%.

**Comment by RoboMWM** [comment]
The tree check is old, and I recommend using [GraviTree](https://www.spigotmc.org/resources/gravitree-prevent-floating-treetop-eyesores.11783/) if you'd like this functionality instead of EHM's version.))
