### ISSUE TITLE
MobReplacement plugin conflict BUG

### ISSUE THREAD

**Issue by Zomblad** [MLG-Fortress/ExtraHardMode#59]
Hello. Today I found 1 GIANT problem. Its a conflict with plugins, that changes mob spawning. So, I tried to change spiders to cave spiders in NORMAL world. I dont know why, but spiders not spawning now at all. I set all monster spawn changes in EHM to 0%, but still no changes. After I uninstall EHM, everything started to work perfectly. Please, fix this problem :(

**Comment by RoboMWM** [comment]
Please detail steps of how to reproduce.

**Comment by Zomblad** [comment]
Hello. Sorry. I actually fixed it, I tried to disable absolutely ALL spawn changes in EHM, and now its works perfect. Please, delete this.

**Comment by RoboMWM** [comment]
Ok, I still don't really know what's going on other than "plugin conflict" and I don't even know what exactly is conflicting...
