### ISSUE TITLE
Armor weight factor no longer working?

### ISSUE THREAD

**Issue by codespunk** [MLG-Fortress/ExtraHardMode#67]
We've recently updated to EHM 3.8.9 and players are reporting that the slowdown you should get while wearing armor no longer functions.

I believe we were previously running 3.8.

**Comment by RoboMWM** [comment]
Test without any other plugins installed. Another plugin could be canceling its tasks (which happened to me once).

**Comment by codespunk** [comment]
According to my players the problem seems to have solved itself,

**Comment by codespunk** [comment]
Another player has clarified the issue. If you have the speed buff from a beacon then it removes the weight debuff even after the sprint buff is gone; you have to remove and re-wear your armor for it to take effect again.

**Comment by RoboMWM** [comment]
Can you please do the test I asked above?

**Comment by codespunk** [comment]
Tested on a fresh Spigot 1.11.2 server with only the latest EHM plugin. Environment consisted of a beacon with Speed 1 buff and a player in full iron.

To clarify, the weight reduction does appear to be working but there was a misunderstanding of how the bug was manifested.

The weight reduction does occur but there is a delay between when it activates and is removed. For example, you move at full speed before and after putting your armor on for a second or two before it takes affect; and you stay slowed down for a second or two before and after taking the armor off.

Here is a video demonstration with slowdown percentage increased to 95% for exaggeration:

https://youtu.be/EKZpS5Jb-ho

**Comment by RoboMWM** [comment]
> The weight reduction does occur but there is a delay between when it activates and is removed.

Yes that's correct, the armor is checked every 3 seconds. This is because there are no events for when a player puts on armor via shift-rightclick, for example.

**Comment by codespunk** [comment]
Thank you for taking the time to look at this and respond. I will consider your words and provide a pull request if I can think of a better solution.

Would it be appropriate to comment here if I have an implementation question regarding the code which handles this event?

**Comment by RoboMWM** [comment]
yea, or PR referencing this issue.
