### ISSUE TITLE
Suggestion: Make better tree felling affect giant musrooms too?

### ISSUE THREAD

**Issue by PsychoLynx** [MLG-Fortress/ExtraHardMode#73]
Title says it - this would be a great toggleable option since (at least in my opinion) giant mushrooms are onstensibly trees.

**Comment by RoboMWM** [comment]
Wouldn't the entire mushroom collapse then?

**Comment by PsychoLynx** [comment]
Err, I guess it would. I'll need to rethink this, I guess ^^"
