### ISSUE TITLE
Pigmen deal no damage for other worlds when whitelist is used

### ISSUE THREAD

**Issue by zhro** [MLG-Fortress/ExtraHardMode#74]
I am currently using EHM by whitelisting it for specific worlds:

```
  Enabled Worlds:
  - someworld
```

This is causing other worlds where it is not enabled to have pigmen which deal no damage.

I have pigmen configured as such:

```
  PigZombies:
    Always Angry: true
    # This simple multiplier allows you to reduce the damage of PigZombies. They are a bit too tough otherwise.
    Dmg to players percent: 70
    # Add netherwart to the drops of pigzombies.
    Always Drop Netherwart In Fortresses: true
    Percent Chance to Drop Netherwart Elsewhere In Nether: 25
    Spawn on Lighting Strikes:
      Enable: true
```

**Comment by RoboMWM** [comment]
version? spigot version?

**Comment by zhro** [comment]
Latest EHM 3.10, latest Spigot 1.11.2. Tested on a non-whitelisted server and a whitelisted server (as described). Disabling EHM make pigmen do damage and re-enabling it caused damage to again stop on non-whitelisted worlds.

**Comment by RoboMWM** [comment]
---
https://github.com/MLG-Fortress/ExtraHardMode/blob/83f43c1ae7ee2a2a4eb8698274b847b3f39e66ff/src/main/java/com/extrahardmode/features/monsters/PigMen.java#L157

Should do a world check before deciding to set damage, or check if getInt is greater than 0. Pretty sure that getInt is returning 0.
