### ISSUE TITLE
[bug] messages still appear even if empty, when chat is visible

### ISSUE THREAD

**Issue by alexchandel** [MLG-Fortress/ExtraHardMode#76]
Even setting a `Msg` to `""` still causes an empty line to be printed if the chat is visible.

Could you add a setting to `messages.yml` that completely disables printing any messages in the chat? This way one doesn't have to blank all the message strings to begin with.

**Comment by RoboMWM** [comment]
Set type to `Disabled` as per the comments at the top of the message.
