### ISSUE TITLE
ScoreBoard

### ISSUE THREAD

**Issue by ShaneBeee** [MLG-Fortress/ExtraHardMode#80]
Hi
So I added feather board onto my server.
A problem I have noticed is when the EHM "scoreboards" show up on the side
i.e... you weigh too much
the feather board goes away
the actual EHM scoreboard doesn't actually show up
then the feather board doesn't come back, I have to manually toggle it off then on again

Would you be able to add it in where a server owner could config it to either print messages to "Scoreboard" or to "chat" .... or maybe even the action bar? OOO yeah, I like that, ACTION BAR

on my server, I would personally rather have it in the CHAT vs scoreboard, as the scoreboard is screwing with Featherboard.
Plus.... a lot of my players, along with myself have mentioned the scoreboard popping up briefly happens too quick they don't notice it, and don't have time to read it
EXAMPLE: when you die "you lost this and that" but it goes away too quick I didn't have a chance to read it
NOW if it were in CHAT... I would be able to see it CLEARLY as well as be able to open chat and see it again

I think this would be REALLY REALLY handy for any server using featherboard or something similar.

Thank you for reading and considering

**Comment by RoboMWM** [comment]
You can have it use chat. See messages.yml.

I will either add an API to allow other plugins to print to other places (bossbar, titles, actionbar, etc.) or add the actionbar option into the plugin. The only issue with the actionbar (and title, bossbar, etc.) is that they are limited in the number of characters they can display (and it also depends on player's font).

**Comment by towncraftserver** [comment]
Hey Robo
I am looking now, and I do not see anything to change it to CHAT vs. Scoreboard
Am I missing something?

**Comment by RoboMWM** [comment]
pretty sure it's something like `use scoreboard`, something named like that, in the `messages.yml` file

**Comment by towncraftserver** [comment]
I see this

`Messages:
  Display Messages In Scoreboard:
    Enable: true
    Scoreboard Title: '&cE-H-S'
    Remove All Color Codes: true`

If I set enable to 'false'
Nothing appears at all, anywhere

**Comment by RoboMWM** [comment]
> Nothing appears at all, anywhere

Weight updates won't appear (too spammy) but the rest should in chat. Test by carrying too much and sitting/swimming in water for example.

**Comment by towncraftserver** [comment]
Duly noted. 
When I get home I will give it a try and test it out.  
I totally understand what you mean about spammy chat with weight.  I have no idea if it's easy/hard to add on... but I know griefPrevention has placeholders is it possible to add a few placeholders to mvdw.  Such as weight?

**Comment by RoboMWM** [comment]
> but I know griefPrevention has placeholders is it possible to add a few placeholders to mvdw

GP does not have any featherboard-specific code. Anyone's free to PR such, or more preferably, create an addon for this (especially since featherboard is a) a paid, non-open-source plugin, and b) has been known to have various conflicts with other server modifications/plugins due to the amount of questionable things it does to the server's internals.)

**Comment by towncraftserver** [comment]
Ah.  Featherboard' creator has a list of placeholders and grief prevention has a category with a bunch  placeholders specific to GP so I'm not sure who made that happen
I don't understand how most of that works anyway 
I'd love to see placeholders made for EHM with weight.   Would be handy.  
No clue who or how that would be done

**Comment by ExusiaiMoe** [comment]
Placeholder is now supported, and you can also use chat instead of scoreboard, this should be fixed
