### ISSUE TITLE
Blocks changed by ore breaking and subsequent physics damage players on top of them

### ISSUE THREAD

**Issue by retrontology** [MLG-Fortress/ExtraHardMode#83]
Hey there, I'm currently experiencing the issue that was previously posted in [#23](https://github.com/MLG-Fortress/ExtraHardMode/issues/23) and [#49](https://github.com/MLG-Fortress/ExtraHardMode/issues/49).

Whenever a player is standing on top of a block that is changed by breaking ore and then applied physics damages the player. I changed the config option **Apply Physics To Weakened Stone** from true to false, reloaded the config, and the damage stopped.

I captured the anomaly [in this video](https://www.youtube.com/watch?v=nJrb-xYVfnA&)

I'm running [Paper Build #1094](https://ci.destroystokyo.com/job/PaperSpigot/1094/) (I also previously experienced this in Build #989) and EHM 3.11.

**Comment by towncraftserver** [comment]
I second this.  
I know know the stand back when I'm mining coal and such

**Comment by RoboMWM** [comment]
This is **not** related to #49 

It is related to #23 - please repost your issue there so all the information on this is consolidated. Thanks!

**Comment by RoboMWM** [comment]
See https://github.com/MLG-Fortress/ExtraHardMode/issues/23#issuecomment-436803232 for details on the fix.
