### ISSUE TITLE
Suggestion Wolves

### ISSUE THREAD

**Issue by towncraftserver** [MLG-Fortress/ExtraHardMode#85]
Another suggestion I believe by Robo back in the day.

Wolves angry at night, very similar to how spiders act.
During the day = nice and friendly "hi cute doggie"
During the night = angry and fierce "oh bad doggy, RUNNNNN!"

**Comment by RoboMWM** [comment]
So, just an fyi, I did get notifications when you commented on the other issues. Thank you for noting your interest.

I am currently swamped with other projects and finals within the next 6 days.

**Comment by towncraftserver** [comment]
Ah duly noted 
Well thank you for replying.  I appreciate it.  
Good luck with your finals :)
