### ISSUE TITLE
Dispensers with water buckets in them can place a permanent water source

### ISSUE THREAD

**Issue by manmadehuman** [MLG-Fortress/ExtraHardMode#87]
If we put a bucket of water in a dispenser and activate, it will leave a permanent water source. 

Thanks!

**Comment by RoboMWM** [comment]
I'm assuming that you want this to function as emptying a bucket normally?

My thinking is if players go to lengths like these (similar to mining ice) then I think it's somewhat deserved? Idk.

**Comment by RoboMWM** [comment]
So this was actually supposed to be stopped by EHM. Spigot changes to the BlockDispenseEvent broke this (`BlockDispenseEvent#getVelocity() returns the location the water source is placed, not its "velocity.")

**Comment by SlimeDog** [comment]
Nice. Thanks.
